"""
tests/test_snapshots.py — Golden-file semantic regression tests.

For each canonical example, `pak explain` generates C code. This test suite
compares the current output to stored golden files in tests/snapshots/.

WHY: `pak check` catches type errors and parse errors, but a semantic change
(e.g., a match arm generates the wrong switch branch, a struct is laid out
wrong) can silently survive `pak check`. Golden snapshots catch these.

UPDATING SNAPSHOTS:
    Run with --update-snapshots to regenerate all golden files:
        pytest tests/test_snapshots.py --update-snapshots

    Or regenerate one file manually:
        pak explain examples/canonical/05_enums.pak > tests/snapshots/05_enums.c

EXPECTATIONS:
- Snapshots change when the compiler's C backend is intentionally modified.
  In that case, regenerate all snapshots in one commit.
- If a snapshot differs unexpectedly, the compiler has a semantic regression.
"""

import re
import subprocess
from pathlib import Path
import pytest

CANONICAL_DIR = Path(__file__).parent.parent / "examples" / "canonical"
SNAPSHOT_DIR  = Path(__file__).parent / "snapshots"


def pytest_addoption(parser):
    parser.addoption(
        "--update-snapshots",
        action="store_true",
        default=False,
        help="Regenerate golden snapshot files instead of comparing.",
    )


_PATH_COMMENT = re.compile(r"^/\* Generated by Pak Compiler - .+ \*/", re.MULTILINE)


def _normalize(c_source: str) -> str:
    """Replace the path-bearing header comment so snapshots are path-independent."""
    return _PATH_COMMENT.sub("/* Generated by Pak Compiler */", c_source)


def _canonical_files():
    return [
        pytest.param(f, id=f.name)
        for f in sorted(CANONICAL_DIR.glob("*.pak"))
    ]


@pytest.mark.parametrize("pak_file", _canonical_files())
def test_explain_matches_snapshot(pak_file, request):
    """Generated C output must match the stored golden snapshot."""
    update = request.config.getoption("--update-snapshots", default=False)

    result = subprocess.run(
        ["pak", "explain", str(pak_file)],
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, (
        f"pak explain failed for {pak_file.name}:\n{result.stderr.strip()}"
    )

    actual = _normalize(result.stdout)

    snapshot_file = SNAPSHOT_DIR / (pak_file.stem + ".c")

    if update:
        snapshot_file.write_text(actual, encoding="utf-8")
        pytest.skip(f"Updated snapshot: {snapshot_file.name}")
        return

    if not snapshot_file.exists():
        pytest.fail(
            f"No snapshot for {pak_file.name}. "
            f"Generate it with: pak explain {pak_file} > {snapshot_file}\n"
            f"Or run: pytest tests/test_snapshots.py --update-snapshots"
        )

    expected = _normalize(snapshot_file.read_text(encoding="utf-8"))

    if actual != expected:
        # Build a human-readable diff
        import difflib
        diff = list(difflib.unified_diff(
            expected.splitlines(keepends=True),
            actual.splitlines(keepends=True),
            fromfile=f"snapshot/{snapshot_file.name}",
            tofile=f"current/{pak_file.name}",
            n=4,
        ))
        diff_str = "".join(diff[:80])  # cap at 80 lines
        if len(diff) > 80:
            diff_str += f"\n... ({len(diff) - 80} more diff lines)\n"

        pytest.fail(
            f"Semantic regression in {pak_file.name} — generated C changed.\n\n"
            f"{diff_str}\n"
            f"If this is intentional, regenerate snapshots:\n"
            f"    pytest tests/test_snapshots.py --update-snapshots"
        )
