"""Generate C header files from Pak module declarations.

For each .pak file with a `module foo.bar` declaration, this produces
a foo_bar.h that other generated .c files can include.  The header
contains forward declarations for all public types and functions.
"""

from pathlib import Path
from typing import List
from . import ast
from .codegen import Codegen, PRIMITIVE_TYPES


def module_to_guard(module_path: str) -> str:
    """'game.player' → 'GAME_PLAYER_H'"""
    return module_path.upper().replace('.', '_') + '_H'


def module_to_filename(module_path: str) -> str:
    """'game.player' → 'game_player.h'"""
    return module_path.replace('.', '_') + '.h'


def generate_header(program: ast.Program, module_path: str) -> str:
    """Generate a C header for a Pak module."""
    guard = module_to_guard(module_path)
    cg = Codegen()

    # First pass: collect enum info for the codegen instance
    for decl in program.decls:
        if isinstance(decl, ast.EnumDecl):
            for v in decl.variants:
                cg.enum_variants[v.name] = decl.name
        elif isinstance(decl, ast.VariantDecl):
            for c in decl.cases:
                cg.enum_variants[c.name] = decl.name

    lines = [
        f'/* Generated by Pak Compiler - {module_path} */',
        f'#ifndef {guard}',
        f'#define {guard}',
        '',
        '#include <stdint.h>',
        '#include <stdbool.h>',
        '',
    ]

    # Emit type declarations (structs, enums, variants)
    for decl in program.decls:
        if isinstance(decl, ast.StructDecl):
            lines.append(cg.gen_struct(decl))
            lines.append('')
        elif isinstance(decl, ast.EnumDecl):
            lines.append(cg.gen_enum(decl))
            lines.append('')
        elif isinstance(decl, ast.VariantDecl):
            lines.append(cg.gen_variant(decl))
            lines.append('')

    # Emit function forward declarations (public functions only)
    for decl in program.decls:
        if isinstance(decl, ast.FnDecl):
            lines.append(_fn_forward_decl(cg, decl, module_path))

    lines += ['', f'#endif /* {guard} */']
    return '\n'.join(lines)


def _fn_forward_decl(cg: Codegen, fn: ast.FnDecl, module_path: str) -> str:
    """Generate a C forward declaration for a function.

    Function names are emitted as-is (no module prefix) so they match
    the names produced by the code generator.
    """
    ret = cg.gen_type(fn.ret_type)
    params = []
    for p in fn.params:
        if isinstance(p.type, ast.TypeArray):
            params.append(cg.gen_array_decl(p.name, p.type))
        else:
            params.append(f'{cg.gen_type(p.type)} {p.name}')
    param_str = ', '.join(params) if params else 'void'
    return f'{ret} {fn.name}({param_str});'


def collect_module_includes(program: ast.Program, all_modules: dict) -> List[str]:
    """
    Return a list of #include lines for all modules used by this program.
    all_modules: {module_path: header_filename}
    """
    includes = []
    for decl in program.decls:
        if isinstance(decl, ast.UseDecl):
            path = decl.path
            if path in all_modules:
                includes.append(f'#include "{all_modules[path]}"')
    return includes
