"""Generate a libdragon-compatible Makefile for a Pak project."""

from pathlib import Path
from typing import List, Optional


def generate_makefile(
    project_name: str,
    rom_title: str,
    c_files: List[Path],          # paths relative to project root
    pakfs_archive: Optional[str],  # filename like "mygame.pakfs", or None
    save_type: str = 'none',
    bit_depth: int = 16,
    resolution: str = '320x240',
    framebuffers: int = 3,
    optimization: str = 'debug',
    use_tiny3d: bool = False,
    project_root: Path = Path('.'),
) -> str:
    """Return the content of a Makefile for this project."""

    # Resolve C source paths relative to project root
    src_list = ' \\\n        '.join(str(f) for f in c_files)

    # Also include the pakfs runtime
    src_list += ' \\\n        runtime/pakfs.c'

    opt_flag = '-O2' if optimization == 'release' else '-g -O0'

    res_w, res_h = resolution.split('x')
    res_define = f'RESOLUTION_{res_w}x{res_h}'
    depth_define = f'DEPTH_{bit_depth}_BPP'

    # ROM header save type string
    save_map = {
        'none':      'EEPROM_4K',   # libdragon default; actual save omitted
        'eeprom4k':  'EEPROM_4K',
        'eeprom16k': 'EEPROM_16K',
        'sram256k':  'SRAM_256K',
        'sram768k':  'SRAM_768K',
        'flashram':  'FLASHRAM',
    }
    save_str = save_map.get(save_type.lower(), 'EEPROM_4K')

    # Asset pipeline rules
    asset_rules = _asset_rules(project_root, use_tiny3d)

    # PakFS packing step
    if pakfs_archive:
        pakfs_rule = _pakfs_rule(project_name, project_root)
    else:
        pakfs_rule = ''

    tiny3d_ldflags = '$(TINY3D_LDFLAGS)' if use_tiny3d else ''
    tiny3d_include = '$(TINY3D_CFLAGS)' if use_tiny3d else ''
    tiny3d_check = ''
    if use_tiny3d:
        tiny3d_check = '''
ifndef TINY3D_INST
$(error TINY3D_INST is not set. Set it to your Tiny3D installation path.)
endif
TINY3D_CFLAGS  := -I$(TINY3D_INST)/include
TINY3D_LDFLAGS := -L$(TINY3D_INST)/lib -lt3d
'''

    dfs_file = f'filesystem/{project_name}.pakfs' if pakfs_archive else ''
    dfs_include = f'\nDFS_FILE        = {dfs_file}' if dfs_file else ''

    return f'''\
# Makefile for {project_name} — generated by Pak compiler
# Requires: libdragon toolchain (https://github.com/DragonMinded/libdragon)
# Usage:
#   make          — build {project_name}.z64
#   make run      — build and launch in ares emulator
#   make clean    — remove build artifacts

include $(N64_INST)/include/n64.mk
{tiny3d_check}
PROJECT_NAME    = {project_name}
ROM_TITLE       = {rom_title[:20]!r}
SAVE_TYPE       = {save_str}

RESOLUTION      = {res_define}
BIT_DEPTH       = {depth_define}
FRAMEBUFFERS    = {framebuffers}

BUILD_DIR       = build
RUNTIME_DIR     = $(shell pak --runtime-dir 2>/dev/null || echo runtime)
{dfs_include}

SRCS = {src_list}

OBJS = $(SRCS:%.c=$(BUILD_DIR)/%.o)
DEPS = $(OBJS:.o=.d)

CFLAGS  += {opt_flag} -Wall -Wextra
CFLAGS  += -DRESOLUTION=$(RESOLUTION) -DBIT_DEPTH=$(BIT_DEPTH)
CFLAGS  += -DFRAMEBUFFERS=$(FRAMEBUFFERS)
CFLAGS  += -I$(RUNTIME_DIR)
CFLAGS  += -I$(BUILD_DIR)
CFLAGS  += {tiny3d_include}

LDFLAGS += {tiny3d_ldflags}

.PHONY: all clean run

all: $(PROJECT_NAME).z64

# Link
$(PROJECT_NAME).elf: $(OBJS)
\t$(CC) $(OBJS) $(LDFLAGS) $(N64_LDFLAGS) -o $@

# ROM
$(PROJECT_NAME).z64: $(PROJECT_NAME).elf{" $(DFS_FILE)" if dfs_file else ""}
\t$(N64TOOL) \\
\t    --title $(ROM_TITLE) \\
\t    --savetype $(SAVE_TYPE) \\
\t    --output $@ \\
\t    --header $(N64_INST)/mips64-elf/lib/header \\
\t    $<{" $(DFS_FILE)" if dfs_file else ""}

# Compile C sources
$(BUILD_DIR)/%.o: %.c
\t@mkdir -p $(dir $@)
\t$(CC) $(CFLAGS) $(N64_CFLAGS) -MMD -c $< -o $@

-include $(DEPS)

{asset_rules}
{pakfs_rule}

run: $(PROJECT_NAME).z64
\tares --system Nintendo64 $<

clean:
\trm -rf $(BUILD_DIR) $(PROJECT_NAME).elf $(PROJECT_NAME).z64{" filesystem/" if dfs_file else ""}
'''


def _asset_rules(root: Path, use_tiny3d: bool) -> str:
    """Return Makefile rules for converting source assets."""
    rules = ['# ── Asset conversion rules ────────────────────────────────────────']

    # Sprites: .png → .sprite
    sprite_rule = '''\
$(BUILD_DIR)/%.sprite: %.png
\t@mkdir -p $(dir $@)
\t$(MKSPRITE) --format RGBA16 --output $@ $<'''
    rules.append(sprite_rule)

    # Audio: .wav → .wav64
    audio_rule = '''\
$(BUILD_DIR)/%.wav64: %.wav
\t@mkdir -p $(dir $@)
\t$(AUDIOCONV64) $< $@

$(BUILD_DIR)/%.xm64: %.xm
\t@mkdir -p $(dir $@)
\t$(AUDIOCONV64) $< $@

$(BUILD_DIR)/%.ym64: %.ym
\t@mkdir -p $(dir $@)
\t$(AUDIOCONV64) $< $@'''
    rules.append(audio_rule)

    if use_tiny3d:
        model_rule = '''\
$(BUILD_DIR)/%.t3dm: %.gltf
\t@mkdir -p $(dir $@)
\t$(T3D_GLTF) $< $@'''
        rules.append(model_rule)

    return '\n\n'.join(rules)


def _pakfs_rule(project_name: str, root: Path) -> str:
    """Return a Makefile rule that runs `pak pack` to build the PakFS archive."""
    return f'''\
# ── PakFS archive ──────────────────────────────────────────────────────────
filesystem/{project_name}.pakfs: $(shell find assets -type f 2>/dev/null)
\t@mkdir -p filesystem
\tpak pack --output $@ assets/'''
