/* Generated by Pak Compiler */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }
enum { MAX_HEALTH = 100 };

static const float SPEED = 2.5f;

static int32_t frame_count = 0;

int main(void) {
    int32_t x = 10;
    float y = 3.14f;
    bool alive = true;
    char * name = "player";
    x = (x + 1);
    y = (y * 2.0f);
    x += 5;
    x -= 2;
    x *= 3;
    x /= 2;
    __auto_type score = 0;
    __auto_type ratio = 0.5f;
    frame_count += 1;
    x = MAX_HEALTH;
    y = SPEED;
    alive = false;
    score = frame_count;
    ratio = (ratio + 1.0f);
    name = "done";
    return 0;
}

