/* Generated by Pak Compiler */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }
int32_t add(int32_t a, int32_t b) {
    return (a + b);
}

float max(float a, float b) {
    if (a > b) {
        return a;
    }
    return b;
}

float clamp(float val, float lo, float hi) {
    if (val < lo) {
        return lo;
    }
    if (val > hi) {
        return hi;
    }
    return val;
}

void reset(int32_t * ptr) {
    *ptr = 0;
}

void increment(int32_t * ptr) {
    *ptr = (*ptr + 1);
}

static int32_t result_sink = 0;

int main(void) {
    result_sink = add(3, 4);
    __auto_type m = max(1.5f, 2.5f);
    __auto_type c = clamp(150.0f, 0.0f, 100.0f);
    int32_t count = 5;
    increment(&count);
    reset(&count);
    result_sink = ((count + (int32_t)m) + (int32_t)c);
    return 0;
}

