/* Generated by Pak Compiler */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }
typedef struct {
    float x;
    float y;
} Vec2;

typedef struct {
    Vec2 pos;
    int32_t health;
    float speed;
    bool alive;
} Player;

void Player_init(Player * self) {
    self->pos.x = 0.0f;
    self->pos.y = 0.0f;
    self->health = 100;
    self->speed = 2.5f;
    self->alive = true;
}

void Player_move(Player * self, float dx, float dy) {
    self->pos.x += dx;
    self->pos.y += dy;
}

bool Player_is_alive(Player * self) {
    return (self->health > 0);
}

void Player_take_damage(Player * self, int32_t amount) {
    self->health -= amount;
    if (self->health <= 0) {
        self->alive = false;
    }
}

static float sink_x = 0.0f;

static int32_t sink_hp = 0;

int main(void) {
    __auto_type p = (Player){.pos = (Vec2){.x = 10.0f, .y = 20.0f}, .health = 100, .speed = 2.5f, .alive = true};
    sink_x = p.pos.x;
    sink_hp = p.health;
    p.move(1.0f, 0.0f);
    p.take_damage(10);
    sink_hp = p.health;
    if (p.is_alive()) {
        sink_hp = p.health;
    }
    return 0;
}

