/* Generated by Pak Compiler */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }
typedef enum {
    Direction_north,
    Direction_south,
    Direction_east,
    Direction_west,
} Direction;

typedef enum {
    GameState_title,
    GameState_playing,
    GameState_paused,
    GameState_gameover,
} GameState;

typedef enum {
    ButtonMask_a = 0x80,
    ButtonMask_b = 0x40,
    ButtonMask_start = 0x10,
    ButtonMask_z = 0x20,
} ButtonMask;

Direction opposite(Direction dir) {
    switch (dir) {
        case Direction_north:
        {
            return Direction_south;
            break;
        }
        case Direction_south:
        {
            return Direction_north;
            break;
        }
        case Direction_east:
        {
            return Direction_west;
            break;
        }
        case Direction_west:
        {
            return Direction_east;
            break;
        }
    }
}

static int32_t sink = 0;

int main(void) {
    __auto_type state = GameState_title;
    __auto_type dir = Direction_north;
    switch (state) {
        case GameState_title:
        {
            sink = 0;
            break;
        }
        case GameState_playing:
        {
            sink = 1;
            break;
        }
        case GameState_paused:
        {
            sink = 2;
            break;
        }
        case GameState_gameover:
        {
            sink = 3;
            break;
        }
    }
    switch (dir) {
        case Direction_north:
        {
            sink = 10;
            break;
        }
        default:
        {
            sink = 11;
            break;
        }
    }
    __auto_type opp = opposite(Direction_east);
    switch (opp) {
        case Direction_west:
        {
            sink = 20;
            break;
        }
        default:
        {
            sink = 21;
            break;
        }
    }
    return 0;
}

