/* Generated by Pak Compiler */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }
typedef enum {
    Entity_tag_player,
    Entity_tag_enemy,
    Entity_tag_projectile,
    Entity_tag_empty,
} Entity_tag;

typedef struct {
    Entity_tag tag;
    union {
    } data;
} Entity;

typedef struct {
    float field0;
} Shape_circle;

typedef struct {
    float field0;
    float field1;
} Shape_rect;

typedef enum {
    Shape_tag_circle,
    Shape_tag_rect,
    Shape_tag_point,
} Shape_tag;

typedef struct {
    Shape_tag tag;
    union {
        Shape_circle circle;
        Shape_rect rect;
    } data;
} Shape;

typedef struct {
    uint8_t field0;
} Event_key_press;

typedef struct {
    int32_t field0;
    int32_t field1;
} Event_mouse_move;

typedef enum {
    Event_tag_key_press,
    Event_tag_mouse_move,
    Event_tag_quit,
} Event_tag;

typedef struct {
    Event_tag tag;
    union {
        Event_key_press key_press;
        Event_mouse_move mouse_move;
    } data;
} Event;

float area(Shape s) {
    switch (s.tag) {
        case /* Shape_circle(r) */:
        {
            return ((r * r) * 3.14159f);
            break;
        }
        case /* Shape_rect(w, h) */:
        {
            return (w * h);
            break;
        }
        case Shape_tag_point:
        {
            return 0.0f;
            break;
        }
    }
}

int32_t entity_id(Entity e) {
    switch (e.tag) {
        case Entity_tag_player:
        {
            return 0;
            break;
        }
        case Entity_tag_enemy:
        {
            return 1;
            break;
        }
        case Entity_tag_projectile:
        {
            return 2;
            break;
        }
        case Entity_tag_empty:
        {
            return 3;
            break;
        }
    }
}

static float sink = 0.0f;

static int32_t sink_i = 0;

int main(void) {
    sink = area(Shape_circle(5.0f));
    sink = area(Shape_rect(4.0f, 3.0f));
    sink = area(Shape_point);
    sink_i = entity_id(Entity_enemy);
    __auto_type e = Event_mouse_move(100, 200);
    switch (e) {
        case /* Event_key_press(k) */:
        {
            sink_i = (int32_t)k;
            break;
        }
        case /* Event_mouse_move(x, y) */:
        {
            sink_i = (x + y);
            break;
        }
        case Event_tag_quit:
        {
            sink_i = -1;
            break;
        }
    }
    return 0;
}

