/* Generated by Pak Compiler */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }
int32_t abs(int32_t x) {
    if (x < 0) {
        return -x;
    }
    return x;
}

int32_t sign(int32_t x) {
    if (x > 0) {
        return 1;
    }
    else if (x < 0) {
        return -1;
    }
    else {
        return 0;
    }
}

static int32_t sink = 0;

int main(void) {
    int32_t x = 5;
    if (x > 10) {
        sink = 1;
    }
    else if (x > 3) {
        sink = 2;
    }
    else {
        sink = 3;
    }
    int32_t count = 0;
    while (true) {
        count += 1;
        if (count >= 10) {
            break;
        }
    }
    int32_t n = 0;
    while (n < 5) {
        n += 1;
    }
    int32_t i = 0;
    do {
        i += 1;
    } while ((i < 3));
    int32_t sum = 0;
    for (int k = 0; k < 10; k++) {
        sum += k;
    }
    for (int k = 0; k < 10; k++) {
        if (k == 5) {
            continue;
        }
        sum += k;
    }
    sink = (((((abs(-3) + sign(x)) + count) + n) + i) + sum);
    return 0;
}

