/* Generated by Pak Compiler */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }
enum { MAP_W = 8 };

int32_t sum_array(int32_t * arr, int32_t len) {
    int32_t total = 0;
    for (int i = 0; i < len; i++) {
        total += arr[i];
    }
    return total;
}

void fill(int32_t * arr, int32_t len, int32_t value) {
    for (int i = 0; i < len; i++) {
        arr[i] = value;
    }
}

static int32_t sink = 0;

int main(void) {
    int32_t scores[8]; /* undefined */
    uint8_t tiles[64]; /* undefined */
    scores[0] = 100;
    scores[1] = 200;
    scores[2] = 50;
    fill(&scores[0], 8, 0);
    tiles[((3 * MAP_W) + 2)] = 5;
    sink = (int32_t)tiles[((3 * MAP_W) + 2)];
    scores[0] = 10;
    scores[1] = 20;
    sink = sum_array(&scores[0], 8);
    return 0;
}

