/* Generated by Pak Compiler */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }
typedef struct {
    int32_t value;
    Node * next;
} Node;

void double_value(int32_t * ptr) {
    *ptr = (*ptr * 2);
}

static int32_t sink = 0;

int main(void) {
    int32_t x = 10;
    int32_t * ptr = &x;
    double_value(ptr);
    sink = (*ptr * ptr) = 99;
    sink = x;
    int32_t * maybe = NULL;
    int32_t * also_maybe = &x;
    if (maybe != NULL) {
        sink = *maybe;
    }
    if (also_maybe != NULL) {
        sink = *also_maybe;
    }
    uint8_t * heap_buf = (uint8_t *)malloc(sizeof(uint8_t) * (size_t)(64));
    free(heap_buf);
    return 0;
}

