/* Generated by Pak Compiler */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }
enum { SCREEN_W = 320 };

enum { SCREEN_H = 240 };

enum { MAX_ENEMIES = 16 };

static const float PI = 3.14159f;

enum { HALF_W = (SCREEN_W / 2) };

enum { HALF_H = (SCREEN_H / 2) };

enum { VERSION = 1 };

static int32_t enemy_count = 0;

static bool game_running = true;

static int32_t score_table[16];

static __attribute__((aligned(16))) uint8_t dma_buffer[4096];

int main(void) {
    enemy_count = (HALF_W + HALF_H);
    enemy_count += 1;
    score_table[0] = 100;
    game_running = (VERSION != 0);
    dma_buffer[0] = (uint8_t)PI;
    score_table[1] = MAX_ENEMIES;
    return 0;
}

