/* Generated by Pak Compiler */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"
#include <display.h>
#include <rdpq.h>
#include <rdpq_gfx.h>
#include <rdpq_sprite.h>
#include <pakfs.h>

/* asset: player_sprite from "sprites/player.png" */
static const char *player_sprite_path = "pak:/sprites/player.png";
/* asset: enemy_sprite from "sprites/enemy.png" */
static const char *enemy_sprite_path = "pak:/sprites/enemy.png";
/* asset: bg_sprite from "sprites/background.png" */
static const char *bg_sprite_path = "pak:/sprites/background.png";


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }
int main(void) {
    display_init(0, 0, 2, 0, 0);
    rdpq_init();
    while (true) {
        __auto_type fb = display_get();
        rdpq_attach_clear(fb);
        rdpq_set_mode_copy();
        rdpq_sprite_blit(bg_sprite, 0, 0, NULL);
        rdpq_sprite_blit(player_sprite, 160, 120, NULL);
        rdpq_sprite_blit(enemy_sprite, 100, 80, NULL);
        rdpq_detach_show();
    }
    return 0;
}

