/* Generated by Pak Compiler - examples/canonical/15_game_loop.pak */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"
#include <display.h>
#include <joypad.h>
#include <rdpq.h>
#include <rdpq_gfx.h>
#include <n64sys.h>
#include <debug.h>

static uint32_t _pak_last_tick = 0;
static inline float _pak_delta_time(void) {
    uint32_t now = TICKS_READ();
    float dt = (float)TIMER_MICROS(now - _pak_last_tick) / 1000000.0f;
    _pak_last_tick = now;
    return dt;
}


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }
typedef struct {
    int32_t x;
    int32_t y;
    bool running;
} GameState;

void update(GameState * gs) {
    __auto_type input = joypad_get_status(0);
    if (input.held.right) {
        gs->x += 2;
    }
    if (input.held.left) {
        gs->x -= 2;
    }
    if (input.held.down) {
        gs->y += 2;
    }
    if (input.held.up) {
        gs->y -= 2;
    }
    if (gs->x < 0) {
        gs->x = 0;
    }
    if (gs->x > 320) {
        gs->x = 320;
    }
    if (gs->y < 0) {
        gs->y = 0;
    }
    if (gs->y > 240) {
        gs->y = 240;
    }
    if (input.pressed.start) {
        gs->running = false;
    }
}

void render(GameState * gs) {
    __auto_type fb = display_get();
    rdpq_attach_clear(fb);
    rdpq_set_mode_fill(0xFF0000FF);
    rdpq_fill_rectangle(gs->x, gs->y, (gs->x + 16), (gs->y + 16));
    rdpq_detach_show();
}

int main(void) {
    display_init(0, 0, 2, 0, 0);
    joypad_init();
    rdpq_init();
    timer_init();
    __auto_type gs = (GameState){.x = 160, .y = 120, .running = true};
    while (true) {
        joypad_poll();
        update(&gs);
        if (!gs.running) {
            break;
        }
        render(&gs);
    }
    rdpq_close();
    debugf("game over");
    return 0;
}

