/* Generated by Pak Compiler - examples/canonical/16_fixed_point.pak */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }
typedef struct {
    int32_t x;
    int32_t y;
} Vec2fx;

Vec2fx vec2fx_add(Vec2fx a, Vec2fx b) {
    return (Vec2fx){.x = (a.x + b.x), .y = (a.y + b.y)};
}

Vec2fx vec2fx_scale(Vec2fx v, int32_t s) {
    return (Vec2fx){.x = (int32_t)(((int64_t)(v.x) * (s)) >> 16), .y = (int32_t)(((int64_t)(v.y) * (s)) >> 16)};
}

static int32_t sink_x = 0.0f;

static int32_t sink_i = 0;

int main(void) {
    int32_t a = 1.5f;
    int32_t b = 2.0f;
    int32_t c = 0.5f;
    __auto_type sum = (a + b);
    __auto_type diff = (a - c);
    __auto_type prod = (int32_t)(((int64_t)(a) * (b)) >> 16);
    __auto_type quot = (int32_t)(((int64_t)(b) << 16) / (a));
    sink_i = (int32_t)a;
    sink_x = (int32_t)3;
    __auto_type pos = (Vec2fx){.x = 10.0f, .y = 5.0f};
    __auto_type vel = (Vec2fx){.x = 1.5f, .y = 0.5f};
    __auto_type next_pos = vec2fx_add(pos, vel);
    __auto_type scaled = vec2fx_scale(vel, 2.0f);
    sink_x = (((((sum + diff) + prod) + quot) + next_pos.x) + scaled.x);
    return 0;
}

