/* Generated by Pak Compiler */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }
__attribute__((hot))
int32_t sum_scanline(uint8_t * buf, int32_t y, int32_t width) {
    int32_t total = 0;
    for (int x = 0; x < width; x++) {
        total += (int32_t)buf[((y * width) + x)];
    }
    return total;
}

typedef struct {
    uint32_t header;
    uint8_t data[60];
} DMAPacket __attribute__((aligned(16)));

static __attribute__((aligned(16))) uint8_t dma_out[4096];

#ifdef DEBUG_MODE
static int32_t debug_counters[16];
#endif  /* DEBUG_MODE */

typedef struct {
    uint8_t data[256];
} CriticalBuffer __attribute__((aligned(8)));

static int32_t sink = 0;

int main(void) {
    __auto_type pkt = (DMAPacket){.header = 0xABCD, .data = /* undefined */};
    dma_out[0] = (uint8_t)pkt.header;
    __auto_type cb = (CriticalBuffer){.data = /* undefined */};
    sink = (int32_t)cb.data[0];
    sink = sum_scanline(&dma_out[0], 0, 320);
    return 0;
}

