/* Generated by Pak Compiler */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"
#include <dma.h>
#include <n64sys.h>


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }
static __attribute__((aligned(16))) uint8_t rx_buffer[4096];

int main(void) {
    data_cache_hit_writeback(&rx_buffer[0], 4096);
    dma_read(&rx_buffer[0], 0x10040000, 4096);
    dma_wait();
    data_cache_hit_invalidate(&rx_buffer[0], 4096);
    __auto_type first = rx_buffer[0];
    rx_buffer[1] = first;
    return 0;
}

