/* Generated by Pak Compiler - examples/canonical/19_traits.pak */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }
/* trait Drawable */
typedef struct {
    void (*draw)(void *, int32_t, int32_t);
    int32_t (*get_width)(void *);
    int32_t (*get_height)(void *);
} Drawable_vtable;

typedef struct {
    void *self;
    const Drawable_vtable *vtable;
} Drawable;

/* trait Updatable */
typedef struct {
    void (*update)(void *, float);
} Updatable_vtable;

typedef struct {
    void *self;
    const Updatable_vtable *vtable;
} Updatable;

typedef struct {
    int32_t x;
    int32_t y;
    int32_t w;
    int32_t h;
} Sprite;

/* impl Sprite for Drawable */
static void _pak_Drawable_draw_Sprite(void *_self, int32_t x, int32_t y) {
    Sprite_draw((Sprite *)_self, x, y);
}

static int32_t _pak_Drawable_get_width_Sprite(void *_self) {
    return Sprite_get_width((Sprite *)_self);
}

static int32_t _pak_Drawable_get_height_Sprite(void *_self) {
    return Sprite_get_height((Sprite *)_self);
}

static const Drawable_vtable _pak_Drawable_vtable_Sprite = {
    .draw = _pak_Drawable_draw_Sprite,
    .get_width = _pak_Drawable_get_width_Sprite,
    .get_height = _pak_Drawable_get_height_Sprite,
};

static inline Drawable Drawable_from_Sprite(Sprite *p) {
    return (Drawable){ .self = (void *)p, .vtable = &_pak_Drawable_vtable_Sprite };
}

typedef struct {
    float x;
    float y;
    float speed;
} Enemy;

/* impl Enemy for Updatable */
static void _pak_Updatable_update_Enemy(void *_self, float dt) {
    Enemy_update((Enemy *)_self, dt);
}

static const Updatable_vtable _pak_Updatable_vtable_Enemy = {
    .update = _pak_Updatable_update_Enemy,
};

static inline Updatable Updatable_from_Enemy(Enemy *p) {
    return (Updatable){ .self = (void *)p, .vtable = &_pak_Updatable_vtable_Enemy };
}

static int32_t sink = 0;

int main(void) {
    __auto_type spr = (Sprite){.x = 0, .y = 0, .w = 16, .h = 16};
    spr.draw(10, 20);
    sink = spr.get_width();
    __auto_type enemy = (Enemy){.x = 0.0f, .y = 0.0f, .speed = 50.0f};
    enemy.update(0.016f);
    sink = (int32_t)enemy.x;
    return 0;
}

