/* Generated by Pak Compiler */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"
#include <display.h>
#include <audio.h>
#include <xm64.h>
#include <wav64.h>
#include <rdpq.h>
#include <rdpq_gfx.h>


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }
static int32_t frame = 0;

int16_t gen_sample(int32_t t) {
    int32_t period = 100;
    if ((t % period) < (period / 2)) {
        return (int16_t)8000;
    }
    return -(int16_t)8000;
}

void fill_audio_buffer(void) {
    int16_t * buf = audio_get_buffer();
    if (buf == NULL) {
        return;
    }
    int32_t i = 0;
    while (true) {
        if (i >= 1470) {
            break;
        }
        int16_t sample = gen_sample(((frame * 735) + (i / 2)));
        buf[i] = sample;
        buf[(i + 1)] = sample;
        i = (i + 2);
    }
}

int main(void) {
    display_init(0, 2, 3, 0, 1);
    rdpq_init();
    audio_init(44100, 4);
    while (true) {
        fill_audio_buffer();
        __auto_type fb = display_get();
        rdpq_attach_clear(fb);
        rdpq_set_mode_fill(0x1A1A2EFF);
        rdpq_fill_rectangle(0, 0, 320, 240);
        rdpq_detach_show();
        frame = (frame + 1);
    }
    return 0;
}

