/* Generated by Pak Compiler - examples/canonical/22_eeprom.pak */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"
#include <eeprom.h>
#include <display.h>
#include <rdpq.h>
#include <rdpq_gfx.h>


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }
enum { SAVE_MAGIC_HI = 0xDE };

enum { SAVE_MAGIC_LO = 0xAD };

enum { SAVE_BLOCK = 0 };

static uint8_t save_magic_0 = 0;

static uint8_t save_magic_1 = 0;

static uint8_t save_score_0 = 0;

static uint8_t save_score_1 = 0;

static uint8_t save_score_2 = 0;

static uint8_t save_score_3 = 0;

static uint8_t save_level = 0;

static uint8_t save_flags = 0;

static __attribute__((aligned(8))) uint8_t eeprom_buf[8];

static int32_t score = 0;

static uint8_t level = 1;

void save_game(void) {
    if (!eeprom.present()) {
        return;
    }
    eeprom_buf[0] = SAVE_MAGIC_HI;
    eeprom_buf[1] = SAVE_MAGIC_LO;
    eeprom_buf[2] = (uint8_t)(score >> 24);
    eeprom_buf[3] = (uint8_t)(score >> 16);
    eeprom_buf[4] = (uint8_t)(score >> 8);
    eeprom_buf[5] = (uint8_t)score;
    eeprom_buf[6] = level;
    eeprom_buf[7] = 0;
    eeprom_write(SAVE_BLOCK, &eeprom_buf[0]);
}

bool load_game(void) {
    if (!eeprom.present()) {
        return false;
    }
    eeprom_read(SAVE_BLOCK, &eeprom_buf[0]);
    if (eeprom_buf[0] != SAVE_MAGIC_HI) {
        return false;
    }
    if (eeprom_buf[1] != SAVE_MAGIC_LO) {
        return false;
    }
    score = (((((int32_t)eeprom_buf[2] << 24) | ((int32_t)eeprom_buf[3] << 16)) | ((int32_t)eeprom_buf[4] << 8)) | (int32_t)eeprom_buf[5]);
    level = eeprom_buf[6];
    return true;
}

int main(void) {
    display_init(0, 2, 2, 0, 0);
    rdpq_init();
    __auto_type loaded = load_game();
    if (!loaded) {
        score = 0;
        level = 1;
    }
    score = (score + 100);
    level = (level + 1);
    save_game();
    while (true) {
        __auto_type fb = display_get();
        rdpq_attach_clear(fb);
        rdpq_set_mode_fill(0x1A1A2EFF);
        rdpq_fill_rectangle(0, 0, 320, 240);
        rdpq_detach_show();
    }
    return 0;
}

