"""Advanced game architecture for N64: large game structure, systems, code organization."""


def gen_advanced_architecture() -> list[dict]:
    pairs = []

    def add(instruction, output):
        pairs.append({"instruction": instruction, "output": output,
                       "source": "generated", "category": "advanced_architecture"})

    # === Game Structure ===
    add("How should I structure a large N64 game in Pak?",
        "Use a layered architecture with clear separation of concerns:\n\n"
        "**Layer 1: Hardware (n64.* modules)**\n"
        "- display, rdpq, controller, audio, timer, dma, cache\n"
        "- Never call these from game logic — go through your abstractions\n\n"
        "**Layer 2: Engine (your utility code)**\n"
        "- math.pak — vector/matrix helpers\n"
        "- pool.pak — object pool implementations\n"
        "- input.pak — input abstraction (maps buttons to game actions)\n"
        "- renderer.pak — wraps rdpq + t3d with your draw calls\n"
        "- audio_mgr.pak — sound effect and music management\n\n"
        "**Layer 3: Game Systems**\n"
        "- physics.pak — movement, gravity, collision\n"
        "- ai.pak — enemy behavior, pathfinding\n"
        "- camera.pak — camera management\n"
        "- inventory.pak — items, equipment\n\n"
        "**Layer 4: Game States**\n"
        "- state_title.pak — title screen\n"
        "- state_game.pak — main gameplay\n"
        "- state_pause.pak — pause menu\n\n"
        "**entry.pak — top-level entry block:**\n"
        "```pak\nentry {\n"
        "    -- init hardware\n    display.init(0, 2, 3, 0, 1)\n"
        "    rdpq.init()\n    controller.init()\n    timer.init()\n    t3d.init()\n\n"
        "    -- init game state machine\n    game_state_machine_init()\n\n"
        "    loop {\n        let dt: f32 = timer.delta()\n"
        "        if dt > 0.033 { dt = 0.033 }\n"
        "        controller.poll()\n        game_state_machine_update(dt)\n"
        "        game_state_machine_render()\n"
        "    }\n}\n```")

    add("How do I implement a game state machine for a complex N64 game?",
        "```pak\nenum GameState {\n"
        "    boot, title, select_file, gameplay,\n"
        "    pause, game_over, cutscene, credits\n}\n\n"
        "static current_state: GameState = GameState.boot\n"
        "static next_state: GameState = GameState.boot\n"
        "static state_timer: f32 = 0.0\n\n"
        "fn request_state(new_state: GameState) {\n"
        "    next_state = new_state\n}\n\n"
        "fn state_machine_update(dt: f32) {\n"
        "    -- handle state transition\n"
        "    if next_state != current_state {\n"
        "        state_exit(current_state)\n"
        "        state_enter(next_state)\n"
        "        current_state = next_state\n"
        "        state_timer = 0.0\n"
        "    }\n\n"
        "    state_timer = state_timer + dt\n\n"
        "    match current_state {\n"
        "        GameState.boot    => { state_boot_update(dt) }\n"
        "        GameState.title   => { state_title_update(dt) }\n"
        "        GameState.gameplay => { state_gameplay_update(dt) }\n"
        "        GameState.pause   => { state_pause_update(dt) }\n"
        "        GameState.game_over => { state_gameover_update(dt) }\n"
        "        GameState.cutscene => { state_cutscene_update(dt) }\n"
        "        GameState.credits  => { state_credits_update(dt) }\n"
        "        _                 => { }\n"
        "    }\n}\n\n"
        "fn state_machine_render() {\n"
        "    let fb = display.get()\n"
        "    rdpq.attach_clear(fb)\n"
        "    match current_state {\n"
        "        GameState.gameplay => { state_gameplay_render() }\n"
        "        GameState.pause    => {\n"
        "            state_gameplay_render()  -- render game underneath\n"
        "            state_pause_render()     -- overlay pause UI\n"
        "        }\n"
        "        _                  => { state_render_generic() }\n"
        "    }\n"
        "    rdpq.detach_show()\n}\n```")

    add("How do I manage game data across state transitions (level loading)?",
        "```pak\n-- Separate persistent data from session data\n\n"
        "struct PersistentData {\n"
        "    -- survives all state changes (loaded from EEPROM)\n"
        "    save_score: i32\n    save_level: i32\n"
        "    options_sfx_vol: i32\n    options_music_vol: i32\n}\n\n"
        "struct SessionData {\n"
        "    -- lives only during a play session\n"
        "    score: i32\n    lives: i32\n"
        "    current_level: i32\n    checkpoint: i32\n"
        "    inventory: Inventory\n}\n\n"
        "struct LevelData {\n"
        "    -- loaded/freed per level\n"
        "    level_model: *T3DModel\n"
        "    enemy_spawn_data: [SpawnPoint; 32]\n"
        "    spawn_count: i32\n}\n\n"
        "static persist: PersistentData = undefined\n"
        "static session: SessionData = undefined\n"
        "static level: LevelData = undefined\n\n"
        "fn load_level(idx: i32) {\n"
        "    -- free previous level data\n"
        "    if level.level_model != none {\n"
        "        t3d.model_free(level.level_model)\n"
        "        level.level_model = none\n"
        "    }\n\n"
        "    -- load new level\n"
        "    session.current_level = idx\n"
        "    -- load model from DragonFS\n}\n```")

    # === Event System ===
    add("How do I implement a simple event system for game communication in Pak?",
        "```pak\nenum EventType {\n"
        "    player_died, enemy_killed, item_picked_up,\n"
        "    level_complete, checkpoint_reached, boss_spawned\n}\n\n"
        "struct GameEvent {\n"
        "    etype: EventType\n    param_a: i32\n    param_b: i32\n}\n\n"
        "const EVENT_QUEUE_SIZE: i32 = 32\n"
        "static event_queue: [GameEvent; 32] = undefined\n"
        "static event_head: i32 = 0\n"
        "static event_tail: i32 = 0\n\n"
        "fn push_event(etype: EventType, a: i32, b: i32) {\n"
        "    let next: i32 = (event_tail + 1) % EVENT_QUEUE_SIZE\n"
        "    if next == event_head { return }  -- queue full, drop\n"
        "    event_queue[event_tail].etype = etype\n"
        "    event_queue[event_tail].param_a = a\n"
        "    event_queue[event_tail].param_b = b\n"
        "    event_tail = next\n}\n\n"
        "fn process_events() {\n"
        "    loop {\n        if event_head == event_tail { break }\n"
        "        let ev: *GameEvent = &event_queue[event_head]\n"
        "        match ev.etype {\n"
        "            EventType.player_died => { handle_player_death(ev.param_a) }\n"
        "            EventType.enemy_killed => {\n"
        "                session.score = session.score + ev.param_b\n"
        "            }\n"
        "            EventType.item_picked_up => { handle_pickup(ev.param_a) }\n"
        "            EventType.level_complete => { request_state(GameState.game_over) }\n"
        "            _ => { }\n"
        "        }\n"
        "        event_head = (event_head + 1) % EVENT_QUEUE_SIZE\n    }\n}\n```")

    # === Pathfinding ===
    add("How do I implement grid-based A* pathfinding for N64 in Pak?",
        "```pak\nconst GRID_W: i32 = 16\nconst GRID_H: i32 = 16\nconst MAX_OPEN: i32 = 64\n\n"
        "struct PathNode {\n    x: i32\n    y: i32\n    g: i32  -- cost from start\n"
        "    h: i32  -- heuristic to goal\n    parent: i32  -- index in closed list\n}\n\n"
        "static grid_blocked: [bool; 256] = undefined  -- 16x16 grid\n"
        "static open_list: [PathNode; 64] = undefined\n"
        "static open_count: i32 = 0\n\n"
        "fn heuristic(ax: i32, ay: i32, bx: i32, by: i32) -> i32 {\n"
        "    let dx: i32 = ax - bx\n    let dy: i32 = ay - by\n"
        "    if dx < 0 { dx = -dx }\n    if dy < 0 { dy = -dy }\n"
        "    return dx + dy  -- Manhattan distance\n}\n\n"
        "fn is_blocked(x: i32, y: i32) -> bool {\n"
        "    if x < 0 or x >= GRID_W or y < 0 or y >= GRID_H {\n"
        "        return true\n    }\n"
        "    return grid_blocked[y * GRID_W + x]\n}\n\n"
        "fn find_path(sx: i32, sy: i32, gx: i32, gy: i32,\n"
        "             out_x: *[i32; 32], out_y: *[i32; 32]) -> i32 {\n"
        "    -- simplified A* that returns step count\n"
        "    -- for N64: limit iterations to stay within frame budget\n"
        "    open_count = 0\n"
        "    let MAX_ITERS: i32 = 32  -- never run more than 32 iterations\n"
        "    let iters: i32 = 0\n\n"
        "    -- add start node\n"
        "    open_list[0].x = sx\n    open_list[0].y = sy\n"
        "    open_list[0].g = 0\n"
        "    open_list[0].h = heuristic(sx, sy, gx, gy)\n"
        "    open_list[0].parent = -1\n    open_count = 1\n\n"
        "    loop {\n        if open_count == 0 or iters >= MAX_ITERS { break }\n"
        "        -- find lowest f = g + h\n"
        "        let best: i32 = 0\n        let bi: i32 = 1\n"
        "        loop {\n            if bi >= open_count { break }\n"
        "            if open_list[bi].g + open_list[bi].h <\n"
        "               open_list[best].g + open_list[best].h {\n"
        "                best = bi\n            }\n            bi = bi + 1\n        }\n\n"
        "        let cur: PathNode = open_list[best]\n"
        "        if cur.x == gx and cur.y == gy {\n"
        "            -- found path\n            return iters\n"
        "        }\n"
        "        -- remove best from open, expand neighbors\n"
        "        open_list[best] = open_list[open_count - 1]\n"
        "        open_count = open_count - 1\n        iters = iters + 1\n    }\n"
        "    return 0\n}\n```\n\n"
        "**Performance note**: Run A* over multiple frames for distant enemies. "
        "Store the path and follow it — don't recalculate every frame.")

    # === Level Streaming ===
    add("How do I implement level streaming for a large N64 world?",
        "N64 can't hold a full large world in RAM. Use sector-based streaming:\n\n"
        "```pak\nconst MAX_LOADED_SECTORS: i32 = 4\nconst SECTOR_LOAD_DIST: f32 = 50.0\n\n"
        "struct Sector {\n    id: i32\n    center_x: f32\n    center_z: f32\n"
        "    model: *T3DModel\n    loaded: bool\n    rom_offset: u32\n    rom_size: u32\n}\n\n"
        "static sectors: [Sector; 16] = undefined\n"
        "static sector_count: i32 = 0\n\n"
        "fn update_streaming(player_x: f32, player_z: f32) {\n"
        "    let i: i32 = 0\n    let loaded_count: i32 = 0\n\n"
        "    -- count loaded sectors\n"
        "    loop {\n        if i >= sector_count { break }\n"
        "        if sectors[i].loaded { loaded_count = loaded_count + 1 }\n"
        "        i = i + 1\n    }\n\n"
        "    i = 0\n    loop {\n        if i >= sector_count { break }\n"
        "        let dx: f32 = sectors[i].center_x - player_x\n"
        "        let dz: f32 = sectors[i].center_z - player_z\n"
        "        let dist_sq: f32 = dx * dx + dz * dz\n\n"
        "        if dist_sq < SECTOR_LOAD_DIST * SECTOR_LOAD_DIST {\n"
        "            if not sectors[i].loaded and loaded_count < MAX_LOADED_SECTORS {\n"
        "                -- load this sector\n"
        "                sectors[i].model = t3d.model_load(sectors[i].model_path)\n"
        "                sectors[i].loaded = true\n"
        "                loaded_count = loaded_count + 1\n"
        "            }\n"
        "        } else {\n"
        "            if sectors[i].loaded {\n"
        "                -- unload distant sector\n"
        "                t3d.model_free(sectors[i].model)\n"
        "                sectors[i].model = none\n"
        "                sectors[i].loaded = false\n"
        "                loaded_count = loaded_count - 1\n"
        "            }\n        }\n        i = i + 1\n    }\n}\n```\n\n"
        "Load sector models from DragonFS. Keep max 3-4 sectors in RAM at once. "
        "Do load/unload one sector per frame to spread the cost.")

    # === Input Abstraction ===
    add("How do I build a clean input abstraction layer in Pak?",
        "```pak\nuse n64.controller\n\n"
        "enum GameButton {\n"
        "    jump, attack, interact, cancel,\n"
        "    menu, use_item, sprint, camera_reset\n}\n\n"
        "struct InputState {\n"
        "    pressed: [bool; 8]   -- just pressed this frame\n"
        "    held: [bool; 8]      -- held down\n"
        "    released: [bool; 8]  -- just released\n"
        "    move_x: f32          -- -1 to 1\n"
        "    move_y: f32          -- -1 to 1\n"
        "    camera_x: f32\n    camera_y: f32\n}\n\n"
        "static input: InputState = undefined\n\n"
        "fn input_update() {\n"
        "    controller.poll()\n"
        "    let pad = controller.read(0)\n\n"
        "    -- map buttons to game actions\n"
        "    let new_jump: bool = pad.held.a\n"
        "    input.pressed[0] = new_jump and not input.held[0]\n"
        "    input.released[0] = not new_jump and input.held[0]\n"
        "    input.held[0] = new_jump\n\n"
        "    let new_attack: bool = pad.held.b\n"
        "    input.pressed[1] = new_attack and not input.held[1]\n"
        "    input.released[1] = not new_attack and input.held[1]\n"
        "    input.held[1] = new_attack\n\n"
        "    -- analog stick with dead zone\n"
        "    let sx: i32 = pad.stick_x as i32\n"
        "    let sy: i32 = pad.stick_y as i32\n"
        "    if sx > 10 or sx < -10 {\n"
        "        input.move_x = (sx as f32) / 80.0\n"
        "    } else {\n        input.move_x = 0.0\n    }\n"
        "    if sy > 10 or sy < -10 {\n"
        "        input.move_y = (sy as f32) / 80.0\n"
        "    } else {\n        input.move_y = 0.0\n    }\n\n"
        "    -- C buttons for camera\n"
        "    if pad.held.c_left { input.camera_x = -1.0 }\n"
        "    elif pad.held.c_right { input.camera_x = 1.0 }\n"
        "    else { input.camera_x = 0.0 }\n}\n\n"
        "fn btn_pressed(b: GameButton) -> bool {\n"
        "    return input.pressed[b as i32]\n}\n"
        "fn btn_held(b: GameButton) -> bool {\n"
        "    return input.held[b as i32]\n}\n```")

    # === Save System Architecture ===
    add("How do I architect a robust save system for N64?",
        "```pak\nuse n64.eeprom\n\n"
        "const SAVE_MAGIC: u32 = 0x504B5356  -- 'PKSV'\n"
        "const SAVE_VERSION: u8 = 1\n"
        "const SAVE_SLOT_SIZE: i32 = 64  -- 64 bytes per slot = 8 EEPROM blocks\n\n"
        "struct SaveSlot {\n"
        "    magic: u32          -- 4 bytes\n"
        "    version: u8         -- 1 byte\n"
        "    slot_index: u8      -- 1 byte\n"
        "    checksum: u16       -- 2 bytes\n"
        "    level: u8           -- 1 byte\n    lives: u8           -- 1 byte\n"
        "    score: i32          -- 4 bytes\n"
        "    flags: u32          -- 4 bytes (bitfield for collected items)\n"
        "    -- total: 18 bytes used, pad to 64\n    pad: [u8; 46]\n}\n\n"
        "fn save_checksum(slot: *SaveSlot) -> u16 {\n"
        "    let sum: u32 = 0\n"
        "    let ptr: *u8 = slot as *u8\n"
        "    let i: i32 = 0\n"
        "    loop {\n        if i >= sizeof(SaveSlot) as i32 { break }\n"
        "        sum = sum + (ptr[i] as u32)\n        i = i + 1\n    }\n"
        "    return (sum & 0xFFFF) as u16\n}\n\n"
        "fn save_write(slot_idx: i32, data: *SaveSlot) -> bool {\n"
        "    if not eeprom.present() { return false }\n"
        "    data.magic = SAVE_MAGIC\n    data.version = SAVE_VERSION\n"
        "    data.slot_index = slot_idx as u8\n    data.checksum = 0\n"
        "    data.checksum = save_checksum(data)\n\n"
        "    -- each EEPROM block = 8 bytes, slot = 8 blocks\n"
        "    let block_start: i32 = slot_idx * 8\n"
        "    let ptr: *u8 = data as *u8\n    let b: i32 = 0\n"
        "    loop {\n        if b >= 8 { break }\n"
        "        eeprom.write(block_start + b, &ptr[b * 8])\n"
        "        b = b + 1\n    }\n    return true\n}\n\n"
        "fn save_read(slot_idx: i32, data: *SaveSlot) -> bool {\n"
        "    if not eeprom.present() { return false }\n"
        "    let block_start: i32 = slot_idx * 8\n"
        "    let ptr: *u8 = data as *u8\n    let b: i32 = 0\n"
        "    loop {\n        if b >= 8 { break }\n"
        "        eeprom.read(block_start + b, &ptr[b * 8])\n"
        "        b = b + 1\n    }\n"
        "    -- validate\n"
        "    if data.magic != SAVE_MAGIC { return false }\n"
        "    let stored: u16 = data.checksum\n    data.checksum = 0\n"
        "    let actual: u16 = save_checksum(data)\n"
        "    data.checksum = stored\n    return stored == actual\n}\n```")

    # === Entity Component Pattern ===
    add("How do I organize entities in a complex N64 game using Pak?",
        "Use a data-oriented entity table instead of object hierarchies:\n\n"
        "```pak\nconst MAX_ENTITIES: i32 = 64\n\n"
        "-- component arrays (struct of arrays, cache-friendly)\n"
        "static ent_active: [bool; 64] = undefined\n"
        "static ent_x: [f32; 64] = undefined\n"
        "static ent_y: [f32; 64] = undefined\n"
        "static ent_z: [f32; 64] = undefined\n"
        "static ent_hp: [i32; 64] = undefined\n"
        "static ent_type: [i32; 64] = undefined  -- 0=player, 1=enemy, 2=item\n"
        "static ent_model: [*T3DModel; 64] = undefined\n"
        "static ent_count: i32 = 0\n\n"
        "fn entity_spawn(type_id: i32, x: f32, y: f32, z: f32,\n"
        "                model: *T3DModel) -> i32 {\n"
        "    let i: i32 = 0\n"
        "    loop {\n        if i >= MAX_ENTITIES { return -1 }\n"
        "        if not ent_active[i] {\n"
        "            ent_active[i] = true\n"
        "            ent_x[i] = x\n            ent_y[i] = y\n"
        "            ent_z[i] = z\n            ent_hp[i] = 100\n"
        "            ent_type[i] = type_id\n"
        "            ent_model[i] = model\n            return i\n"
        "        }\n        i = i + 1\n    }\n    return -1\n}\n\n"
        "fn entity_kill(idx: i32) {\n    ent_active[idx] = false\n}\n\n"
        "fn update_all_entities(dt: f32) {\n"
        "    let i: i32 = 0\n"
        "    loop {\n        if i >= MAX_ENTITIES { break }\n"
        "        if ent_active[i] {\n"
        "            if ent_type[i] == 1 {  -- enemy\n"
        "                update_enemy_entity(i, dt)\n"
        "            }\n        }\n        i = i + 1\n    }\n}\n\n"
        "fn draw_all_entities() {\n"
        "    let i: i32 = 0\n"
        "    loop {\n        if i >= MAX_ENTITIES { break }\n"
        "        if ent_active[i] and ent_model[i] != none {\n"
        "            t3d.model_draw(ent_model[i])\n"
        "        }\n        i = i + 1\n    }\n}\n```\n\n"
        "Struct-of-arrays layout is more cache-friendly than array-of-structs "
        "when iterating all entities of the same type.")

    # === Cutscene System ===
    add("How do I implement a cutscene system in Pak?",
        "```pak\nenum CutsceneCmd {\n"
        "    cmd_wait, cmd_move_camera, cmd_play_anim,\n"
        "    cmd_show_text, cmd_fade_out, cmd_end\n}\n\n"
        "struct CutsceneStep {\n    cmd: CutsceneCmd\n"
        "    param_a: f32\n    param_b: f32\n    param_c: f32\n"
        "    text: *c_char\n    duration: f32\n}\n\n"
        "struct Cutscene {\n"
        "    steps: *CutsceneStep\n    step_count: i32\n"
        "    current_step: i32\n    step_timer: f32\n"
        "    playing: bool\n}\n\n"
        "static active_cutscene: Cutscene = undefined\n\n"
        "fn cutscene_start(steps: *CutsceneStep, count: i32) {\n"
        "    active_cutscene.steps = steps\n"
        "    active_cutscene.step_count = count\n"
        "    active_cutscene.current_step = 0\n"
        "    active_cutscene.step_timer = 0.0\n"
        "    active_cutscene.playing = true\n}\n\n"
        "fn cutscene_update(dt: f32) {\n"
        "    if not active_cutscene.playing { return }\n"
        "    let step: *CutsceneStep = &active_cutscene.steps[active_cutscene.current_step]\n"
        "    active_cutscene.step_timer = active_cutscene.step_timer + dt\n\n"
        "    match step.cmd {\n"
        "        CutsceneCmd.cmd_wait => { }\n"
        "        CutsceneCmd.cmd_show_text => { }\n"
        "        CutsceneCmd.cmd_end => {\n"
        "            active_cutscene.playing = false\n"
        "            request_state(GameState.gameplay)\n        }\n"
        "        _ => { }\n    }\n\n"
        "    if active_cutscene.step_timer >= step.duration {\n"
        "        active_cutscene.current_step = active_cutscene.current_step + 1\n"
        "        active_cutscene.step_timer = 0.0\n"
        "        if active_cutscene.current_step >= active_cutscene.step_count {\n"
        "            active_cutscene.playing = false\n"
        "        }\n    }\n}\n```")

    return pairs
