"""Complex game architecture: AI, pathfinding, physics, inventory, dialog, level streaming."""


def gen_complex_architecture() -> list[dict]:
    pairs = []

    def add(instruction, output):
        pairs.append({"instruction": instruction, "output": output,
                       "source": "generated", "category": "complex_architecture"})

    # === AI Systems ===
    add("How do I implement enemy AI with a state machine in Pak?",
        "```pak\nenum AIState { idle, patrol, chase, attack, flee, dead }\n\n"
        "struct Enemy {\n    x: f32\n    y: f32\n    z: f32\n"
        "    hp: i32\n    state: AIState\n"
        "    patrol_x: f32\n    patrol_z: f32\n"
        "    target_x: f32\n    target_z: f32\n"
        "    state_timer: f32\n    attack_cooldown: f32\n}\n\n"
        "fn ai_update(e: *Enemy, player_x: f32, player_z: f32, dt: f32) {\n"
        "    let dx: f32 = player_x - e.x\n"
        "    let dz: f32 = player_z - e.z\n"
        "    let dist_sq: f32 = dx * dx + dz * dz\n"
        "    e.state_timer = e.state_timer + dt\n"
        "    e.attack_cooldown = e.attack_cooldown - dt\n"
        "    if e.attack_cooldown < 0.0 { e.attack_cooldown = 0.0 }\n\n"
        "    match e.state {\n"
        "        AIState.idle => {\n"
        "            if dist_sq < 2500.0 { e.state = AIState.chase }\n"
        "            if e.state_timer > 3.0 {\n"
        "                e.state = AIState.patrol\n"
        "                e.state_timer = 0.0\n"
        "            }\n        }\n"
        "        AIState.patrol => {\n"
        "            -- move toward patrol point\n"
        "            let px: f32 = e.patrol_x - e.x\n"
        "            let pz: f32 = e.patrol_z - e.z\n"
        "            e.x = e.x + px * 0.02\n"
        "            e.z = e.z + pz * 0.02\n"
        "            if dist_sq < 2500.0 { e.state = AIState.chase }\n"
        "            if px * px + pz * pz < 4.0 {\n"
        "                e.state = AIState.idle\n"
        "                e.state_timer = 0.0\n"
        "            }\n        }\n"
        "        AIState.chase => {\n"
        "            e.x = e.x + dx * 0.03\n"
        "            e.z = e.z + dz * 0.03\n"
        "            if dist_sq < 100.0 and e.attack_cooldown <= 0.0 {\n"
        "                e.state = AIState.attack\n"
        "                e.state_timer = 0.0\n"
        "            }\n"
        "            if dist_sq > 10000.0 {\n"
        "                e.state = AIState.idle\n"
        "                e.state_timer = 0.0\n"
        "            }\n        }\n"
        "        AIState.attack => {\n"
        "            if e.state_timer > 0.5 {\n"
        "                e.attack_cooldown = 2.0\n"
        "                e.state = AIState.chase\n"
        "                e.state_timer = 0.0\n"
        "            }\n        }\n"
        "        AIState.flee => {\n"
        "            e.x = e.x - dx * 0.04\n"
        "            e.z = e.z - dz * 0.04\n"
        "        }\n"
        "        AIState.dead => { }\n"
        "    }\n\n"
        "    if e.hp <= 0 { e.state = AIState.dead }\n"
        "    if e.hp < 3 and e.state != AIState.dead {\n"
        "        e.state = AIState.flee\n    }\n}\n```")

    add("How do I implement a waypoint patrol system in Pak?",
        "```pak\nconst MAX_WAYPOINTS: i32 = 8\n\n"
        "struct PatrolRoute {\n"
        "    points_x: [f32; 8]\n    points_z: [f32; 8]\n"
        "    count: i32\n    current: i32\n"
        "    wait_time: f32\n    wait_timer: f32\n}\n\n"
        "fn patrol_update(route: *PatrolRoute, x: *f32, z: *f32, dt: f32,\n"
        "                 speed: f32) -> bool {\n"
        "    if route.wait_timer > 0.0 {\n"
        "        route.wait_timer = route.wait_timer - dt\n"
        "        return false\n    }\n\n"
        "    let tx: f32 = route.points_x[route.current]\n"
        "    let tz: f32 = route.points_z[route.current]\n"
        "    let dx: f32 = tx - *x\n"
        "    let dz: f32 = tz - *z\n"
        "    let dist_sq: f32 = dx * dx + dz * dz\n\n"
        "    if dist_sq < 4.0 {\n"
        "        route.current = route.current + 1\n"
        "        if route.current >= route.count { route.current = 0 }\n"
        "        route.wait_timer = route.wait_time\n"
        "        return true  -- reached waypoint\n"
        "    }\n\n"
        "    -- move toward current waypoint\n"
        "    let step: f32 = speed * dt\n"
        "    *x = *x + dx * 0.05 * step\n"
        "    *z = *z + dz * 0.05 * step\n"
        "    return false\n}\n```")

    # === Physics ===
    add("How do I implement 3D physics with gravity and collision in Pak?",
        "```pak\nstruct PhysicsBody {\n"
        "    x: f32\n    y: f32\n    z: f32\n"
        "    vx: f32\n    vy: f32\n    vz: f32\n"
        "    radius: f32\n    grounded: bool\n}\n\n"
        "const GRAVITY: f32 = -20.0\n"
        "const FLOOR_Y: f32 = 0.0\n"
        "const FRICTION: f32 = 0.9\n\n"
        "fn physics_update(body: *PhysicsBody, dt: f32) {\n"
        "    -- apply gravity\n"
        "    body.vy = body.vy + GRAVITY * dt\n\n"
        "    -- integrate velocity\n"
        "    body.x = body.x + body.vx * dt\n"
        "    body.y = body.y + body.vy * dt\n"
        "    body.z = body.z + body.vz * dt\n\n"
        "    -- floor collision\n"
        "    if body.y < FLOOR_Y {\n"
        "        body.y = FLOOR_Y\n"
        "        body.vy = 0.0\n"
        "        body.grounded = true\n"
        "    } else {\n"
        "        body.grounded = false\n"
        "    }\n\n"
        "    -- friction on ground\n"
        "    if body.grounded {\n"
        "        body.vx = body.vx * FRICTION\n"
        "        body.vz = body.vz * FRICTION\n"
        "    }\n}\n\n"
        "fn sphere_vs_sphere(a: *PhysicsBody, b: *PhysicsBody) -> bool {\n"
        "    let dx: f32 = a.x - b.x\n"
        "    let dy: f32 = a.y - b.y\n"
        "    let dz: f32 = a.z - b.z\n"
        "    let dist_sq: f32 = dx * dx + dy * dy + dz * dz\n"
        "    let r: f32 = a.radius + b.radius\n"
        "    return dist_sq < r * r\n}\n```")

    add("How do I implement AABB collision detection for 3D in Pak?",
        "```pak\nstruct AABB {\n"
        "    min_x: f32\n    min_y: f32\n    min_z: f32\n"
        "    max_x: f32\n    max_y: f32\n    max_z: f32\n}\n\n"
        "fn aabb_overlap(a: *AABB, b: *AABB) -> bool {\n"
        "    if a.max_x < b.min_x or a.min_x > b.max_x { return false }\n"
        "    if a.max_y < b.min_y or a.min_y > b.max_y { return false }\n"
        "    if a.max_z < b.min_z or a.min_z > b.max_z { return false }\n"
        "    return true\n}\n\n"
        "fn aabb_from_pos(x: f32, y: f32, z: f32,\n"
        "                 hw: f32, hh: f32, hd: f32, out: *AABB) {\n"
        "    out.min_x = x - hw\n    out.max_x = x + hw\n"
        "    out.min_y = y - hh\n    out.max_y = y + hh\n"
        "    out.min_z = z - hd\n    out.max_z = z + hd\n}\n\n"
        "fn resolve_aabb(mover: *AABB, obstacle: *AABB,\n"
        "                vx: *f32, vy: *f32, vz: *f32) {\n"
        "    if not aabb_overlap(mover, obstacle) { return }\n"
        "    -- push out on smallest overlap axis\n"
        "    let ox: f32 = mover.max_x - obstacle.min_x\n"
        "    let oy: f32 = mover.max_y - obstacle.min_y\n"
        "    let oz: f32 = mover.max_z - obstacle.min_z\n"
        "    if ox < oy and ox < oz {\n"
        "        *vx = 0.0\n"
        "    } elif oy < oz {\n"
        "        *vy = 0.0\n"
        "    } else {\n"
        "        *vz = 0.0\n"
        "    }\n}\n```")

    # === Inventory System ===
    add("How do I implement an inventory system for an N64 game in Pak?",
        "```pak\nconst MAX_ITEMS: i32 = 20\n"
        "const MAX_STACK: i32 = 99\n\n"
        "enum ItemType {\n"
        "    none_item, health_potion, mana_potion, key,\n"
        "    sword, shield, arrow, bomb, hookshot, boomerang\n}\n\n"
        "struct ItemSlot {\n    item: ItemType\n    count: i32\n}\n\n"
        "struct Inventory {\n"
        "    slots: [ItemSlot; 20]\n    slot_count: i32\n"
        "    selected: i32\n}\n\n"
        "impl Inventory {\n"
        "    fn init(self: *Inventory) {\n"
        "        self.slot_count = 0\n        self.selected = 0\n"
        "        let i: i32 = 0\n"
        "        loop {\n            if i >= MAX_ITEMS { break }\n"
        "            self.slots[i].item = ItemType.none_item\n"
        "            self.slots[i].count = 0\n"
        "            i = i + 1\n        }\n    }\n\n"
        "    fn add_item(self: *Inventory, item: ItemType, count: i32) -> bool {\n"
        "        -- try stacking first\n"
        "        let i: i32 = 0\n"
        "        loop {\n            if i >= self.slot_count { break }\n"
        "            if self.slots[i].item == item {\n"
        "                self.slots[i].count = self.slots[i].count + count\n"
        "                if self.slots[i].count > MAX_STACK {\n"
        "                    self.slots[i].count = MAX_STACK\n"
        "                }\n                return true\n"
        "            }\n            i = i + 1\n        }\n\n"
        "        -- add to new slot\n"
        "        if self.slot_count >= MAX_ITEMS { return false }\n"
        "        self.slots[self.slot_count].item = item\n"
        "        self.slots[self.slot_count].count = count\n"
        "        self.slot_count = self.slot_count + 1\n"
        "        return true\n    }\n\n"
        "    fn remove_item(self: *Inventory, item: ItemType, count: i32) -> bool {\n"
        "        let i: i32 = 0\n"
        "        loop {\n            if i >= self.slot_count { break }\n"
        "            if self.slots[i].item == item {\n"
        "                self.slots[i].count = self.slots[i].count - count\n"
        "                if self.slots[i].count <= 0 {\n"
        "                    self.slots[i].item = ItemType.none_item\n"
        "                    self.slots[i].count = 0\n"
        "                }\n                return true\n"
        "            }\n            i = i + 1\n        }\n"
        "        return false\n    }\n\n"
        "    fn has_item(self: *Inventory, item: ItemType) -> bool {\n"
        "        let i: i32 = 0\n"
        "        loop {\n            if i >= self.slot_count { break }\n"
        "            if self.slots[i].item == item and self.slots[i].count > 0 {\n"
        "                return true\n            }\n"
        "            i = i + 1\n        }\n"
        "        return false\n    }\n}\n```")

    # === Dialog System ===
    add("How do I implement a dialog/text box system for N64 in Pak?",
        "```pak\nuse n64.rdpq\n\nconst MAX_DIALOG_LEN: i32 = 128\n"
        "const CHARS_PER_LINE: i32 = 28\n"
        "const BOX_X: i32 = 20\nconst BOX_Y: i32 = 160\n"
        "const BOX_W: i32 = 280\nconst BOX_H: i32 = 60\n\n"
        "struct DialogBox {\n"
        "    text: [c_char; 128]\n    text_len: i32\n"
        "    chars_shown: i32\n    active: bool\n"
        "    timer: f32\n    speed: f32\n}\n\n"
        "impl DialogBox {\n"
        "    fn init(self: *DialogBox) {\n"
        "        self.active = false\n        self.chars_shown = 0\n"
        "        self.timer = 0.0\n        self.speed = 15.0  -- chars/second\n"
        "    }\n\n"
        "    fn show(self: *DialogBox, msg: *c_char, len: i32) {\n"
        "        let i: i32 = 0\n"
        "        loop {\n            if i >= len or i >= MAX_DIALOG_LEN - 1 { break }\n"
        "            self.text[i] = msg[i]\n"
        "            i = i + 1\n        }\n"
        "        self.text[i] = 0 as c_char\n"
        "        self.text_len = len\n        self.chars_shown = 0\n"
        "        self.active = true\n        self.timer = 0.0\n    }\n\n"
        "    fn update(self: *DialogBox, dt: f32, a_pressed: bool) {\n"
        "        if not self.active { return }\n"
        "        if self.chars_shown < self.text_len {\n"
        "            self.timer = self.timer + self.speed * dt\n"
        "            self.chars_shown = self.timer as i32\n"
        "            if self.chars_shown > self.text_len {\n"
        "                self.chars_shown = self.text_len\n            }\n"
        "            -- A button shows all text immediately\n"
        "            if a_pressed { self.chars_shown = self.text_len }\n"
        "        } else {\n"
        "            -- all text shown, A closes dialog\n"
        "            if a_pressed { self.active = false }\n"
        "        }\n    }\n\n"
        "    fn draw(self: *DialogBox) {\n"
        "        if not self.active { return }\n"
        "        -- draw box background\n"
        "        rdpq.set_mode_fill(0x000000C0)  -- semi-transparent black\n"
        "        rdpq.fill_rectangle(BOX_X, BOX_Y, BOX_X + BOX_W, BOX_Y + BOX_H)\n"
        "        -- text would be drawn with rdpq_font here\n"
        "    }\n}\n```")

    # === Level/Room System ===
    add("How do I implement a room-based level system in Pak?",
        "```pak\nconst MAX_ROOMS: i32 = 16\nconst MAX_DOORS: i32 = 4\n\n"
        "struct Door {\n"
        "    x: f32\n    z: f32\n    width: f32\n"
        "    target_room: i32\n    spawn_x: f32\n    spawn_z: f32\n}\n\n"
        "struct Room {\n"
        "    active: bool\n    model_path: *c_char\n"
        "    model: *T3DModel\n"
        "    doors: [Door; 4]\n    door_count: i32\n"
        "    enemy_start: i32\n    enemy_count: i32\n}\n\n"
        "static rooms: [Room; 16] = undefined\n"
        "static current_room: i32 = 0\n\n"
        "fn load_room(idx: i32) {\n"
        "    -- unload previous room\n"
        "    if rooms[current_room].model != none {\n"
        "        t3d.model_free(rooms[current_room].model)\n"
        "        rooms[current_room].model = none\n"
        "    }\n\n"
        "    -- load new room\n"
        "    rooms[idx].model = t3d.model_load(rooms[idx].model_path)\n"
        "    current_room = idx\n}\n\n"
        "fn check_doors(player_x: f32, player_z: f32) {\n"
        "    let room: *Room = &rooms[current_room]\n"
        "    let i: i32 = 0\n"
        "    loop {\n        if i >= room.door_count { break }\n"
        "        let door: *Door = &room.doors[i]\n"
        "        let dx: f32 = player_x - door.x\n"
        "        let dz: f32 = player_z - door.z\n"
        "        if dx * dx + dz * dz < door.width * door.width {\n"
        "            load_room(door.target_room)\n"
        "            -- teleport player to spawn point\n"
        "            return\n"
        "        }\n        i = i + 1\n    }\n}\n```\n\n"
        "Only one room model is loaded at a time to conserve memory. "
        "Doors trigger room transitions with spawn points.")

    # === Weapon System ===
    add("How do I implement a weapon system like Perfect Dark in Pak?",
        "```pak\nconst MAX_WEAPONS: i32 = 8\n\n"
        "enum WeaponType {\n"
        "    none_weapon, pistol, shotgun, rifle, rocket_launcher,\n"
        "    sniper, grenade, melee\n}\n\n"
        "struct WeaponDef {\n"
        "    wtype: WeaponType\n    damage: i32\n    fire_rate: f32\n"
        "    ammo_max: i32\n    range: f32\n    spread: f32\n"
        "    is_automatic: bool\n}\n\n"
        "struct WeaponState {\n"
        "    def: *WeaponDef\n    ammo: i32\n"
        "    cooldown: f32\n    reloading: bool\n"
        "    reload_timer: f32\n}\n\n"
        "struct WeaponInventory {\n"
        "    weapons: [WeaponState; 8]\n"
        "    count: i32\n    current: i32\n}\n\n"
        "fn weapon_fire(ws: *WeaponState) -> bool {\n"
        "    if ws.cooldown > 0.0 { return false }\n"
        "    if ws.ammo <= 0 { return false }\n"
        "    if ws.reloading { return false }\n\n"
        "    ws.ammo = ws.ammo - 1\n"
        "    ws.cooldown = ws.def.fire_rate\n"
        "    return true\n}\n\n"
        "fn weapon_update(ws: *WeaponState, dt: f32) {\n"
        "    if ws.cooldown > 0.0 {\n"
        "        ws.cooldown = ws.cooldown - dt\n"
        "    }\n"
        "    if ws.reloading {\n"
        "        ws.reload_timer = ws.reload_timer - dt\n"
        "        if ws.reload_timer <= 0.0 {\n"
        "            ws.ammo = ws.def.ammo_max\n"
        "            ws.reloading = false\n"
        "        }\n    }\n}\n\n"
        "fn weapon_switch(inv: *WeaponInventory, dir: i32) {\n"
        "    inv.current = inv.current + dir\n"
        "    if inv.current >= inv.count { inv.current = 0 }\n"
        "    if inv.current < 0 { inv.current = inv.count - 1 }\n}\n```")

    # === Objective System ===
    add("How do I implement a mission objective system in Pak?",
        "```pak\nconst MAX_OBJECTIVES: i32 = 8\n\n"
        "enum ObjectiveState { locked, active, completed, failed }\n\n"
        "struct Objective {\n"
        "    name: *c_char\n    description: *c_char\n"
        "    state: ObjectiveState\n    required: bool  -- must complete to win\n}\n\n"
        "struct Mission {\n"
        "    objectives: [Objective; 8]\n"
        "    count: i32\n}\n\n"
        "impl Mission {\n"
        "    fn complete_objective(self: *Mission, idx: i32) {\n"
        "        if idx >= 0 and idx < self.count {\n"
        "            self.objectives[idx].state = ObjectiveState.completed\n"
        "        }\n    }\n\n"
        "    fn fail_objective(self: *Mission, idx: i32) {\n"
        "        if idx >= 0 and idx < self.count {\n"
        "            self.objectives[idx].state = ObjectiveState.failed\n"
        "        }\n    }\n\n"
        "    fn is_mission_complete(self: *Mission) -> bool {\n"
        "        let i: i32 = 0\n"
        "        loop {\n            if i >= self.count { break }\n"
        "            if self.objectives[i].required {\n"
        "                if self.objectives[i].state != ObjectiveState.completed {\n"
        "                    return false\n"
        "                }\n            }\n"
        "            i = i + 1\n        }\n"
        "        return true\n    }\n\n"
        "    fn is_mission_failed(self: *Mission) -> bool {\n"
        "        let i: i32 = 0\n"
        "        loop {\n            if i >= self.count { break }\n"
        "            if self.objectives[i].required {\n"
        "                if self.objectives[i].state == ObjectiveState.failed {\n"
        "                    return true\n"
        "                }\n            }\n"
        "            i = i + 1\n        }\n"
        "        return false\n    }\n}\n```")

    # === HUD System ===
    add("How do I implement a HUD overlay for a 3D game in Pak?",
        "```pak\nuse n64.rdpq\n\nextern \"C\" {\n"
        "    fn rdpq_mode_push()\n    fn rdpq_mode_pop()\n"
        "    fn rdpq_text_printf(x: i32, y: i32, font: i32, fmt: *c_char, ...) -> i32\n}\n\n"
        "struct HUD {\n    health: i32\n    max_health: i32\n"
        "    ammo: i32\n    score: i32\n    show_crosshair: bool\n}\n\n"
        "fn draw_hud(hud: *HUD) {\n"
        "    rdpq_mode_push()\n"
        "    rdpq.set_mode_standard()\n\n"
        "    -- health bar background\n"
        "    rdpq.set_mode_fill(0x400000FF)  -- dark red\n"
        "    rdpq.fill_rectangle(10, 10, 110, 20)\n\n"
        "    -- health bar fill\n"
        "    let bar_w: i32 = (hud.health * 100) / hud.max_health\n"
        "    rdpq.set_mode_fill(0xFF0000FF)  -- bright red\n"
        "    rdpq.fill_rectangle(10, 10, 10 + bar_w, 20)\n\n"
        "    -- ammo counter\n"
        "    rdpq_text_printf(250, 220, 1, \"%d\", hud.ammo)\n\n"
        "    -- score\n"
        "    rdpq_text_printf(10, 220, 1, \"Score: %d\", hud.score)\n\n"
        "    -- crosshair\n"
        "    if hud.show_crosshair {\n"
        "        rdpq.set_mode_fill(0xFFFFFFFF)\n"
        "        rdpq.fill_rectangle(158, 118, 162, 122)  -- center dot\n"
        "    }\n\n"
        "    rdpq_mode_pop()\n}\n```\n\n"
        "Use rdpq_mode_push/pop to save and restore 3D render state. "
        "Draw HUD after t3d.frame_end() but before rdpq.detach_show().")

    # === Spawn System ===
    add("How do I implement an enemy spawn/wave system in Pak?",
        "```pak\nconst MAX_ENEMIES: i32 = 16\n\n"
        "struct SpawnWave {\n"
        "    enemy_count: i32\n    spawn_delay: f32\n"
        "    spawned: i32\n    timer: f32\n}\n\n"
        "struct SpawnSystem {\n"
        "    waves: [SpawnWave; 8]\n    wave_count: i32\n"
        "    current_wave: i32\n    enemies_alive: i32\n}\n\n"
        "impl SpawnSystem {\n"
        "    fn update(self: *SpawnSystem, dt: f32) {\n"
        "        if self.current_wave >= self.wave_count { return }\n\n"
        "        let wave: *SpawnWave = &self.waves[self.current_wave]\n"
        "        wave.timer = wave.timer + dt\n\n"
        "        if wave.timer >= wave.spawn_delay and wave.spawned < wave.enemy_count {\n"
        "            -- spawn an enemy\n"
        "            wave.spawned = wave.spawned + 1\n"
        "            wave.timer = 0.0\n"
        "            self.enemies_alive = self.enemies_alive + 1\n"
        "        }\n\n"
        "        -- advance wave when all enemies defeated\n"
        "        if wave.spawned >= wave.enemy_count and self.enemies_alive <= 0 {\n"
        "            self.current_wave = self.current_wave + 1\n"
        "        }\n    }\n}\n```")

    return pairs
