"""Integrated multi-system examples: combining AI, physics, audio, save, 3D together."""


def gen_integrated_games() -> list[dict]:
    pairs = []

    def add(instruction, output):
        pairs.append({"instruction": instruction, "output": output,
                       "source": "generated", "category": "integrated"})

    add("How do I combine physics, AI, audio, and save in one N64 game loop?",
        "The key is a clear update order every frame:\n\n"
        "```pak\nuse n64.display\nuse n64.controller\nuse n64.rdpq\nuse n64.timer\n"
        "use n64.audio\nuse n64.mixer\nuse t3d\n\n"
        "entry {\n"
        "    -- 1. Init hardware in correct order\n"
        "    display.init(0, 2, 3, 0, 1)\n    rdpq.init()\n"
        "    controller.init()\n    timer.init()\n"
        "    audio.init(44100, 3)\n    mixer.init(8)\n    t3d.init()\n\n"
        "    -- 2. Init game systems\n"
        "    save_system_init()\n    audio_manager_init()\n"
        "    physics_world_init()\n    entity_system_init()\n\n"
        "    -- 3. Load level assets\n"
        "    load_level(0)\n\n"
        "    loop {\n        let dt: f32 = timer.delta()\n"
        "        if dt > 0.033 { dt = 0.033 }  -- cap delta time\n\n"
        "        -- 4. Fill audio buffer FIRST (most time-critical)\n"
        "        let abuf = audio.get_buffer()\n"
        "        if abuf != none {\n            mixer.poll(*abuf)\n        }\n\n"
        "        -- 5. Read input\n"
        "        controller.poll()\n        let pad = controller.read(0)\n"
        "        input_update(&pad)\n\n"
        "        -- 6. Update game logic\n"
        "        player_update(dt)\n        physics_update_all(dt)\n"
        "        ai_update_all(dt)\n        collision_resolve_all()\n"
        "        event_process_all()\n\n"
        "        -- 7. Render\n"
        "        let fb = display.get()\n        rdpq.attach_clear(fb)\n"
        "        t3d.frame_start()\n        t3d.viewport_attach(&viewport)\n"
        "        render_world()\n        render_entities()\n"
        "        t3d.frame_end()\n        render_hud()\n"
        "        rdpq.detach_show()\n    }\n}\n```\n\n"
        "**Order matters:**\n"
        "1. Audio buffer fill comes first — most time-critical, avoid starvation\n"
        "2. Input read second — fresh data for all systems\n"
        "3. Physics before collision — integrate positions before resolving\n"
        "4. Events after everything — process side-effects last\n"
        "5. Render last — draw the final state")

    add("How do I build a complete mini action game with enemies, audio, and saving?",
        "Here's the architecture for a complete mini action game:\n\n"
        "```pak\n-- Systems init:\n"
        "-- 1. display.init(0, 2, 3, 0, 1)\n"
        "-- 2. rdpq.init() + t3d.init()\n"
        "-- 3. audio.init(44100, 3) + mixer.init(8)\n"
        "-- 4. Load assets: player model, enemy model, SFX, music\n"
        "-- 5. Load save data from EEPROM\n\n"
        "-- Per-frame update order:\n"
        "fn game_update(dt: f32) {\n"
        "    -- audio first\n"
        "    let abuf = audio.get_buffer()\n"
        "    if abuf != none { mixer.poll(*abuf) }\n\n"
        "    -- input\n"
        "    controller.poll()\n    let pad = controller.read(0)\n\n"
        "    -- player\n    player_update(dt, &pad)\n\n"
        "    -- enemies\n    let i: i32 = 0\n"
        "    loop {\n        if i >= enemy_count { break }\n"
        "        if enemies[i].active {\n"
        "            enemy_ai_update(&enemies[i], dt)\n"
        "            -- check if enemy can see player\n"
        "            let dx: f32 = player.x - enemies[i].x\n"
        "            let dz: f32 = player.z - enemies[i].z\n"
        "            let dist: f32 = dx * dx + dz * dz\n"
        "            if dist < 900.0 {  -- within 30 units\n"
        "                enemies[i].state = EnemyState.chase\n"
        "            }\n            if enemies[i].hp <= 0 {\n"
        "                enemies[i].active = false\n"
        "                score = score + 100\n"
        "                -- play death sound on any free channel\n"
        "                play_sfx_on_free_channel(&sfx_enemy_die)\n"
        "            }\n        }\n        i = i + 1\n    }\n\n"
        "    -- bullets\n    bullets_update(dt)\n\n"
        "    -- auto-save at checkpoints\n"
        "    if player_reached_checkpoint() {\n"
        "        save_game_state()\n"
        "        rumble.start(0)  -- rumble feedback\n"
        "        -- stop rumble after 0.3s\n"
        "    }\n}\n\n"
        "fn game_render() {\n"
        "    let fb = display.get()\n    rdpq.attach_clear(fb)\n"
        "    t3d.frame_start()\n    t3d.viewport_attach(&viewport)\n"
        "    -- set lighting\n    t3d.light_set_ambient(40, 40, 60)\n"
        "    t3d.light_set_directional(0, 255, 240, 200, -0.5, -1.0, 0.3)\n"
        "    t3d.light_set_count(1)\n"
        "    -- draw level\n    t3d.model_draw(level_model)\n"
        "    -- draw enemies\n    let i: i32 = 0\n"
        "    loop {\n        if i >= enemy_count { break }\n"
        "        if enemies[i].active { t3d.model_draw(enemy_model) }\n"
        "        i = i + 1\n    }\n"
        "    -- draw player\n    t3d.skeleton_draw(&player_skel, player_model)\n"
        "    t3d.frame_end()\n    -- HUD\n    render_hud()\n"
        "    rdpq.detach_show()\n}\n```")

    add("How do I integrate all N64 audio systems — SFX, music, and positional sound?",
        "```pak\nuse n64.audio\nuse n64.mixer\nuse n64.wav64\nuse n64.xm64\n\n"
        "-- Channel layout:\n-- 0: reserved for xm64 music (managed by xm64player internally)\n"
        "-- 1-3: positional/3D sound effects\n"
        "-- 4-6: UI/non-positional SFX\n-- 7: ambient loop\n\n"
        "struct AudioManager {\n    sfx_footstep: wav64_t\n    sfx_shot: wav64_t\n"
        "    sfx_explosion: wav64_t\n    sfx_pickup: wav64_t\n"
        "    music: xm64player_t\n    master_volume: f32\n    music_volume: f32\n}\n\n"
        "static audio_mgr: AudioManager = undefined\n\n"
        "fn audio_manager_init() {\n"
        "    audio.init(44100, 3)\n    mixer.init(16)\n\n"
        "    wav64_open(&audio_mgr.sfx_footstep, \"rom:/sfx/step.wav64\")\n"
        "    wav64_open(&audio_mgr.sfx_shot, \"rom:/sfx/shot.wav64\")\n"
        "    wav64_open(&audio_mgr.sfx_explosion, \"rom:/sfx/boom.wav64\")\n"
        "    wav64_open(&audio_mgr.sfx_pickup, \"rom:/sfx/pickup.wav64\")\n\n"
        "    xm64player_open(&audio_mgr.music, \"rom:/music/theme.xm64\")\n"
        "    xm64player_play(&audio_mgr.music, 0)  -- music starts on ch 0\n\n"
        "    audio_mgr.master_volume = 1.0\n    audio_mgr.music_volume = 0.7\n}\n\n"
        "fn play_sfx_3d(sfx: *wav64_t, src_x: f32, src_z: f32,\n"
        "               cam_x: f32, cam_z: f32, ch: i32) {\n"
        "    let dx: f32 = src_x - cam_x\n    let dz: f32 = src_z - cam_z\n"
        "    let dist: f32 = dx * dx + dz * dz\n"
        "    if dist > 40000.0 { return }  -- too far, skip\n\n"
        "    -- volume falloff with distance\n"
        "    let vol: f32 = 1.0 - dist / 40000.0\n"
        "    if vol < 0.0 { vol = 0.0 }\n"
        "    let pan: f32 = dx / 200.0  -- left/right pan\n"
        "    if pan < -1.0 { pan = -1.0 }\n    if pan > 1.0 { pan = 1.0 }\n\n"
        "    if not mixer.ch_playing(ch) {\n"
        "        wav64_play(sfx, ch)\n"
        "        mixer.ch_set_vol(ch, vol * audio_mgr.master_volume,\n"
        "                         vol * audio_mgr.master_volume)\n"
        "    }\n}\n\n"
        "fn audio_update() {\n    -- fill audio buffer every frame\n"
        "    let buf = audio.get_buffer()\n"
        "    if buf != none {\n        mixer.poll(*buf)\n    }\n}\n```")

    add("How do I implement a complete 3-slot save system with validation?",
        "```pak\nuse n64.eeprom\n\nconst SAVE_MAGIC: u32 = 0x4E36534F  -- 'N6SO'\n"
        "const SLOTS: i32 = 3\n"
        "-- Each slot = 8 EEPROM blocks = 64 bytes\n-- 3 slots = 24 blocks (needs 4KB EEPROM)\n\n"
        "struct SaveSlot {\n"
        "    magic: u32      -- 4\n    checksum: u32   -- 4\n"
        "    level: u8       -- 1\n    lives: u8       -- 1\n"
        "    flags: u16      -- 2\n    score: i32      -- 4\n"
        "    play_time: u32  -- 4 (seconds)\n"
        "    pad: [u8; 44]   -- pad to 64 bytes\n}\n\n"
        "fn slot_checksum(s: *SaveSlot) -> u32 {\n"
        "    let old: u32 = s.checksum\n    s.checksum = 0\n"
        "    let sum: u32 = 0\n    let ptr: *u8 = s as *u8\n    let i: i32 = 0\n"
        "    loop {\n        if i >= sizeof(SaveSlot) as i32 { break }\n"
        "        sum = sum + (ptr[i] as u32)\n        i = i + 1\n    }\n"
        "    s.checksum = old\n    return sum\n}\n\n"
        "fn save_write(slot: i32, data: *SaveSlot) -> bool {\n"
        "    if not eeprom.present() { return false }\n"
        "    if slot < 0 or slot >= SLOTS { return false }\n\n"
        "    data.magic = SAVE_MAGIC\n"
        "    data.checksum = slot_checksum(data)\n"
        "    let block: i32 = slot * 8\n    let ptr: *u8 = data as *u8\n"
        "    let b: i32 = 0\n"
        "    loop {\n        if b >= 8 { break }\n"
        "        eeprom.write(block + b, &ptr[b * 8])\n        b = b + 1\n    }\n"
        "    return true\n}\n\n"
        "fn save_read(slot: i32, data: *SaveSlot) -> bool {\n"
        "    if not eeprom.present() { return false }\n"
        "    if slot < 0 or slot >= SLOTS { return false }\n\n"
        "    let block: i32 = slot * 8\n    let ptr: *u8 = data as *u8\n"
        "    let b: i32 = 0\n"
        "    loop {\n        if b >= 8 { break }\n"
        "        eeprom.read(block + b, &ptr[b * 8])\n        b = b + 1\n    }\n\n"
        "    if data.magic != SAVE_MAGIC { return false }\n"
        "    let expected: u32 = slot_checksum(data)\n"
        "    return expected == data.checksum\n}\n\n"
        "fn save_slot_exists(slot: i32) -> bool {\n"
        "    let data: SaveSlot = undefined\n    return save_read(slot, &data)\n}\n\n"
        "fn save_delete(slot: i32) {\n"
        "    if not eeprom.present() { return }\n"
        "    let empty: SaveSlot = undefined\n    empty.magic = 0\n"
        "    save_write(slot, &empty)\n}\n```")

    add("How do I combine t3d 3D rendering with 2D HUD elements in the same frame?",
        "```pak\nuse n64.display\nuse n64.rdpq\nuse t3d\n\n"
        "extern \"C\" {\n    fn rdpq_mode_push()\n    fn rdpq_mode_pop()\n"
        "    fn rdpq_text_printf(x: i32, y: i32, font: i32,\n"
        "                        fmt: *c_char, ...) -> i32\n}\n\n"
        "fn render_full_frame(player_hp: i32, score: i32, ammo: i32) {\n"
        "    let fb = display.get()\n    rdpq.attach_clear(fb)\n\n"
        "    -- === 3D SCENE ===\n"
        "    t3d.frame_start()\n    t3d.viewport_attach(&viewport)\n\n"
        "    -- lighting\n    t3d.light_set_ambient(50, 50, 70)\n"
        "    t3d.light_set_directional(0, 255, 245, 220, -0.4, -1.0, 0.3)\n"
        "    t3d.light_set_count(1)\n\n"
        "    -- draw 3D world\n    t3d.model_draw(level_model)\n"
        "    t3d.skeleton_draw(&player_skel, player_model)\n"
        "    let i: i32 = 0\n    loop {\n"
        "        if i >= enemy_count { break }\n"
        "        if enemies[i].active { t3d.model_draw(enemy_model) }\n"
        "        i = i + 1\n    }\n\n"
        "    t3d.frame_end()\n\n"
        "    -- === 2D HUD (after t3d.frame_end, before detach_show) ===\n"
        "    rdpq_mode_push()  -- save 3D render state\n"
        "    rdpq.set_mode_standard()\n\n"
        "    -- health bar\n"
        "    rdpq.set_mode_fill(0x200000FF)\n"
        "    rdpq.fill_rectangle(8, 8, 108, 18)\n"
        "    let hbar: i32 = player_hp\n    if hbar < 0 { hbar = 0 }\n"
        "    rdpq.set_mode_fill(0xFF2020FF)\n"
        "    rdpq.fill_rectangle(8, 8, 8 + hbar, 18)\n\n"
        "    -- score text\n"
        "    rdpq_text_printf(120, 8, 1, \"SCORE %06d\", score)\n\n"
        "    -- ammo count\n"
        "    rdpq_text_printf(270, 220, 1, \"%d\", ammo)\n\n"
        "    -- crosshair\n    rdpq.set_mode_fill(0xFFFFFFFF)\n"
        "    rdpq.fill_rectangle(157, 118, 163, 122)\n\n"
        "    rdpq_mode_pop()  -- restore 3D render state\n\n"
        "    rdpq.detach_show()\n}\n```\n\n"
        "**Key rule**: `t3d.frame_end()` must come before 2D HUD rendering. "
        "Use `rdpq_mode_push/pop` to avoid corrupting the 3D render state.")

    add("How should I handle multiple player controllers and local multiplayer on N64?",
        "```pak\nuse n64.controller\n\nconst NUM_PLAYERS: i32 = 2\n\n"
        "struct PlayerState {\n    active: bool\n    x: f32\n    y: f32\n    z: f32\n"
        "    hp: i32\n    score: i32\n}\n\n"
        "static players: [PlayerState; 4] = undefined\nstatic player_count: i32 = 0\n\n"
        "fn detect_players() {\n"
        "    controller.poll()\n    player_count = 0\n    let i: i32 = 0\n"
        "    loop {\n        if i >= 4 { break }\n"
        "        -- check if controller has any input (button held or stick moved)\n"
        "        let pad = controller.read(i)\n"
        "        let active: bool = pad.held.a or pad.held.b or pad.held.start\n"
        "        if active {\n            players[i].active = true\n"
        "            player_count = player_count + 1\n"
        "        }\n        i = i + 1\n    }\n}\n\n"
        "fn update_all_players(dt: f32) {\n"
        "    controller.poll()\n    let i: i32 = 0\n"
        "    loop {\n        if i >= 4 { break }\n"
        "        if players[i].active {\n"
        "            let pad = controller.read(i)\n"
        "            update_player(i, &pad, dt)\n        }\n        i = i + 1\n    }\n}\n\n"
        "fn render_splitscreen() {\n"
        "    if player_count == 1 {\n"
        "        -- full screen\n        render_player_view(0, 0, 0, 320, 240)\n"
        "    } elif player_count == 2 {\n"
        "        -- top/bottom split\n"
        "        render_player_view(0, 0, 0, 320, 120)\n"
        "        render_player_view(1, 0, 120, 320, 120)\n"
        "    } elif player_count == 4 {\n"
        "        -- 4-way split\n"
        "        render_player_view(0, 0, 0, 160, 120)\n"
        "        render_player_view(1, 160, 0, 160, 120)\n"
        "        render_player_view(2, 0, 120, 160, 120)\n"
        "        render_player_view(3, 160, 120, 160, 120)\n"
        "    }\n}\n\n"
        "fn render_player_view(player: i32, x: i32, y: i32, w: i32, h: i32) {\n"
        "    t3d.frame_start()\n    t3d.screen_projection(x, y, w, h)\n"
        "    t3d.viewport_attach(&player_viewports[player])\n"
        "    -- draw world from this player's camera perspective\n"
        "    t3d.frame_end()\n}\n```")

    add("How do I make the game respond differently based on N64 hardware config?",
        "```pak\nextern \"C\" {\n    fn sys_get_memory_size() -> i32\n"
        "    fn sys_get_tv_type() -> i32  -- 0=PAL, 1=NTSC, 2=MPAL\n}\n\n"
        "struct HardwareConfig {\n    has_expansion_pak: bool\n"
        "    is_pal: bool\n    controller_count: i32\n}\n\n"
        "static hw_config: HardwareConfig = undefined\n\n"
        "fn detect_hardware() {\n"
        "    hw_config.has_expansion_pak = sys_get_memory_size() >= 8388608\n"
        "    hw_config.is_pal = sys_get_tv_type() == 0\n\n"
        "    -- count connected controllers\n    controller.poll()\n"
        "    hw_config.controller_count = 0\n    let i: i32 = 0\n"
        "    loop {\n        if i >= 4 { break }\n"
        "        let pad = controller.read(i)\n"
        "        if pad.held.start or pad.held.a {\n"
        "            hw_config.controller_count = hw_config.controller_count + 1\n"
        "        }\n        i = i + 1\n    }\n}\n\n"
        "fn get_game_settings() {\n"
        "    if hw_config.has_expansion_pak {\n"
        "        -- 8MB: load high-res textures, more enemies on screen\n"
        "        max_enemies = 24\n        texture_quality = 2\n"
        "    } else {\n"
        "        -- 4MB: conservative settings\n"
        "        max_enemies = 8\n        texture_quality = 1\n"
        "    }\n\n"
        "    if hw_config.is_pal {\n"
        "        -- PAL runs at 50Hz, adjust timing\n"
        "        -- display.init with PAL resolution\n"
        "        target_fps = 50\n    } else {\n"
        "        target_fps = 60\n    }\n}\n```\n\n"
        "Always detect hardware at boot. Expansion Pak enables: more entities, "
        "higher-res textures, larger level geometry, more audio channels.")

    return pairs
