"""N64 performance optimization: RAM budgets, TMEM, polygons, profiling, fixed-point."""


def gen_performance_optimization() -> list[dict]:
    pairs = []

    def add(instruction, output):
        pairs.append({"instruction": instruction, "output": output,
                       "source": "generated", "category": "performance"})

    # === Memory Budget ===
    add("What is the N64 memory budget I should plan around?",
        "N64 has 4MB RAM by default (8MB with Expansion Pak). Budget carefully:\n\n"
        "**Typical 4MB breakdown:**\n"
        "- OS/libdragon overhead: ~256KB\n"
        "- Triple framebuffers (320x240 16bpp): 3 × 150KB = 450KB\n"
        "- Z-buffer (if used): 150KB\n"
        "- Audio buffers: ~32KB\n"
        "- Code + BSS + stack: ~256-512KB\n"
        "- Available for game data: ~2.5-3MB\n\n"
        "**Typical 8MB breakdown (Expansion Pak):**\n"
        "- Same overhead as above\n"
        "- Available for game data: ~6.5-7MB\n\n"
        "**Track your budget in Pak:**\n"
        "```pak\n-- rough budget constants\n"
        "const FRAMEBUF_SIZE: i32 = 153600  -- 320*240*2\n"
        "const ZBUF_SIZE: i32 = 153600\n"
        "const AUDIO_BUF: i32 = 32768\n"
        "const GAME_RAM: i32 = 2621440  -- ~2.5MB remaining\n```\n\n"
        "Always check memory use with `pak explain` to see struct sizes. "
        "Expansion Pak detection: `sys.expandedRam()` returns true if present.")

    add("How do I check if the Expansion Pak is installed in Pak?",
        "```pak\nextern \"C\" {\n"
        "    fn sys_get_memory_size() -> i32\n}\n\n"
        "const BASE_RAM: i32 = 4194304   -- 4MB\n"
        "const EXPAND_RAM: i32 = 8388608 -- 8MB\n\n"
        "fn has_expansion_pak() -> bool {\n"
        "    return sys_get_memory_size() >= EXPAND_RAM\n}\n\n"
        "entry {\n    if has_expansion_pak() {\n"
        "        -- can load higher-res textures, more entities\n"
        "    } else {\n"
        "        -- use lower-quality assets, fewer entities\n"
        "    }\n}\n```\n\n"
        "Check at startup and scale your game's asset quality accordingly. "
        "Never assume Expansion Pak is present for core gameplay.")

    add("How do I minimize heap allocations for performance on N64?",
        "Heap allocation (alloc/free) is slow and causes fragmentation. Prefer:\n\n"
        "**1. Static pools over dynamic allocation:**\n"
        "```pak\n-- bad: allocates/frees every spawn\n"
        "fn spawn_bullet() -> *Bullet {\n"
        "    return alloc(Bullet)\n}\n\n"
        "-- good: fixed pool, O(1) allocation\n"
        "static bullet_pool: [Bullet; 32] = undefined\n"
        "static bullet_free: i32 = 0\n\n"
        "fn pool_spawn() -> *Bullet {\n"
        "    let i: i32 = 0\n"
        "    loop {\n        if i >= 32 { return none }\n"
        "        if not bullet_pool[i].active {\n"
        "            bullet_pool[i].active = true\n"
        "            return &bullet_pool[i]\n"
        "        }\n        i = i + 1\n    }\n"
        "    return none\n}\n```\n\n"
        "**2. Stack allocation for temporaries:**\n"
        "```pak\nfn compute_path() {\n"
        "    let tmp_nodes: [PathNode; 16] = undefined  -- on stack\n"
        "    -- use tmp_nodes...\n"
        "    -- auto freed at end of function\n}\n```\n\n"
        "**3. Load all assets at level start, free only at level end.**")

    # === TMEM / Texture ===
    add("What are the TMEM limits for N64 textures?",
        "TMEM (Texture Memory) is only **4096 bytes (4KB)** — this is the single "
        "biggest performance constraint for N64 3D.\n\n"
        "**Texture size limits by format:**\n"
        "| Format | Max Size | Notes |\n"
        "|---|---|---|\n"
        "| RGBA16 (16bpp) | 64×64 | Standard for most textures |\n"
        "| RGBA32 (32bpp) | 32×64 | Half TMEM per row |\n"
        "| CI4 (4-bit indexed) | 128×64 | With 16-entry palette |\n"
        "| CI8 (8-bit indexed) | 64×64 | With 256-entry palette |\n"
        "| IA4 / IA8 | 128×64 / 64×64 | Intensity+alpha |\n"
        "| I4 / I8 | 128×128 / 64×128 | Intensity only |\n\n"
        "**Key rules:**\n"
        "- Textures must be power-of-2 dimensions\n"
        "- TMEM holds at most ~2 full 64×64 RGBA16 textures at once\n"
        "- Use CI4 (4-bit palette) for color sprites to fit more in TMEM\n"
        "- Use I4/I8 for grayscale elements (fonts, shadows)\n"
        "- t3d batches TMEM loads — draw same-texture objects together")

    add("How do I optimize texture usage in a t3d scene?",
        "**Sort draw calls by texture to minimize TMEM reloads:**\n\n"
        "```pak\n-- bad: alternating textures thrash TMEM\n"
        "t3d.model_draw(enemy_a)   -- texture A\n"
        "t3d.model_draw(player)    -- texture B (reload TMEM)\n"
        "t3d.model_draw(enemy_b)   -- texture A (reload again!)\n\n"
        "-- good: group by texture\n"
        "t3d.model_draw(enemy_a)   -- texture A\n"
        "t3d.model_draw(enemy_b)   -- texture A (no reload)\n"
        "t3d.model_draw(player)    -- texture B (one reload)\n```\n\n"
        "**Use texture atlases for sprites/HUD:**\n"
        "Pack multiple small images into one 64×64 texture and use UV offsets. "
        "One TMEM load serves all HUD elements.\n\n"
        "**Reuse textures across models:**\n"
        "Different enemy types sharing the same skin texture = zero TMEM reload cost. "
        "Differentiate with vertex colors instead of unique textures.")

    # === Polygon Budget ===
    add("What polygon counts should I target for N64 games?",
        "N64 RDP can process roughly **100,000-200,000 triangles/second** but "
        "practical limits are much lower due to fill rate:\n\n"
        "**Per-frame polygon budget (60fps target):**\n"
        "- Total triangles on screen: **500-1500 max** for smooth 60fps\n"
        "- A player character: 100-300 tris\n"
        "- An enemy: 50-150 tris\n"
        "- A level section: 200-500 tris visible at once\n"
        "- Sky/background: 20-50 tris (flat-shaded, no texture)\n\n"
        "**Real N64 game references:**\n"
        "- Mario 64 Mario model: ~700 tris\n"
        "- GoldenEye level sections: ~200-400 tris visible\n"
        "- Rogue Squadron ships: ~400-800 tris\n\n"
        "**Rules:**\n"
        "- LOD is essential for complex scenes — reduce at distance\n"
        "- Flat-shaded (no texture) tris are nearly free fillrate-wise\n"
        "- Textured + lit tris cost the most\n"
        "- Billboard sprites for distant objects (trees, items, enemies)")

    add("How do I profile frame rate in a Pak game?",
        "```pak\nuse n64.timer\nuse n64.rdpq\n\nextern \"C\" {\n"
        "    fn rdpq_text_printf(x: i32, y: i32, font: i32,\n"
        "                        fmt: *c_char, ...) -> i32\n}\n\n"
        "static frame_count: i32 = 0\n"
        "static fps_timer: f32 = 0.0\n"
        "static last_fps: i32 = 0\n\n"
        "fn update_fps(dt: f32) {\n"
        "    frame_count = frame_count + 1\n"
        "    fps_timer = fps_timer + dt\n"
        "    if fps_timer >= 1.0 {\n"
        "        last_fps = frame_count\n"
        "        frame_count = 0\n"
        "        fps_timer = fps_timer - 1.0\n"
        "    }\n}\n\n"
        "fn draw_fps() {\n"
        "    rdpq_text_printf(5, 5, 1, \"FPS: %d\", last_fps)\n}\n\n"
        "-- in main loop:\n"
        "let dt: f32 = timer.delta()\n"
        "update_fps(dt)\n"
        "-- ... game logic ...\n"
        "-- ... render ...\n"
        "draw_fps()   -- shows FPS overlay\n```\n\n"
        "Target: 60fps (dt ≈ 0.0167). If dropping to 30fps (dt ≈ 0.033), "
        "reduce polygon count, LOD distances, or entity counts.")

    # === Fixed-Point Math ===
    add("When should I use fixed-point instead of float on N64?",
        "The N64 CPU has a hardware FPU but floating-point operations are still "
        "2-4x slower than integer operations. Use fixed-point for:\n\n"
        "**Use fixed-point (fix16.16) for:**\n"
        "- Physics simulation (gravity, velocity, position for many entities)\n"
        "- Tile/grid coordinates\n"
        "- Scroll positions\n"
        "- Anything updated for 16+ objects per frame\n\n"
        "**Use float (f32) for:**\n"
        "- t3d matrix math (already optimized by the library)\n"
        "- One-off calculations\n"
        "- Angles and trigonometry\n"
        "- Camera systems\n\n"
        "```pak\n-- fixed-point physics for many enemies:\nstruct EnemyFP {\n"
        "    x: fix16.16\n    y: fix16.16\n"
        "    vx: fix16.16\n    vy: fix16.16\n}\n\n"
        "const GRAVITY_FP: fix16.16 = -20.0\n\n"
        "fn update_enemy_fp(e: *EnemyFP, dt: fix16.16) {\n"
        "    e.vy = e.vy + GRAVITY_FP * dt\n"
        "    e.x = e.x + e.vx * dt\n"
        "    e.y = e.y + e.vy * dt\n}\n```")

    add("How do I avoid expensive operations in tight loops on N64?",
        "**Operations to avoid in per-frame loops:**\n\n"
        "```pak\n-- BAD: square root every frame per entity\nfn normalize_slow(x: *f32, y: *f32) {\n"
        "    -- sqrt is very slow!\n"
        "    let len: f32 = sqrt(*x * *x + *y * *y)\n"
        "    *x = *x / len\n    *y = *y / len\n}\n\n"
        "-- GOOD: use squared distance for comparisons\nfn in_range_sq(ax: f32, az: f32,\n"
        "               bx: f32, bz: f32, range: f32) -> bool {\n"
        "    let dx: f32 = ax - bx\n    let dz: f32 = az - bz\n"
        "    return dx * dx + dz * dz < range * range\n"
        "    -- no sqrt needed!\n}\n```\n\n"
        "**Other optimizations:**\n"
        "- Use `i32` instead of `f32` for counters, indices, flags\n"
        "- Precompute sin/cos tables for repeated angle lookups\n"
        "- Limit active entity updates: skip AI when off-screen\n"
        "- Use early-exit loops: break as soon as you find what you need\n"
        "- Avoid alloc/free per frame — use pools\n"
        "- Batch similar draw calls together (same texture, same mode)")

    # === Display Lists / RDP ===
    add("How does rdpq batching work and why does it matter?",
        "rdpq automatically batches RDP commands into a display list. "
        "Mode switches (fill→texture→standard) are expensive — minimize them:\n\n"
        "```pak\nuse n64.rdpq\n\n-- BAD: mode switches every draw\nfn draw_mixed_bad() {\n"
        "    rdpq.set_mode_fill(0xFF0000FF)\n    rdpq.fill_rectangle(10, 10, 50, 50)\n"
        "    rdpq.set_mode_standard()\n    -- draw sprite\n"
        "    rdpq.set_mode_fill(0x00FF00FF)\n    rdpq.fill_rectangle(60, 10, 100, 50)\n"
        "    rdpq.set_mode_standard()\n    -- draw another sprite\n}\n\n"
        "-- GOOD: group same-mode draws together\nfn draw_mixed_good() {\n"
        "    -- all fills first\n"
        "    rdpq.set_mode_fill(0xFF0000FF)\n    rdpq.fill_rectangle(10, 10, 50, 50)\n"
        "    rdpq.set_mode_fill(0x00FF00FF)\n    rdpq.fill_rectangle(60, 10, 100, 50)\n"
        "    -- then all sprites\n"
        "    rdpq.set_mode_standard()\n    -- draw all sprites here\n}\n```\n\n"
        "The RDP processes commands in parallel with the CPU — a well-batched "
        "frame lets both CPU and RDP stay busy, doubling effective throughput.")

    add("How do I keep a stable 60fps in Pak?",
        "60fps = 16.67ms per frame. N64 CPU runs at 93.75MHz.\n\n"
        "**Frame time budget:**\n"
        "- CPU game logic: ~4ms\n"
        "- RSP (t3d transform): ~3ms\n"
        "- RDP (fill/texture): ~5ms\n"
        "- Overhead/sync: ~4ms\n\n"
        "**Cap delta time to avoid spiral of death:**\n"
        "```pak\nuse n64.timer\n\nconst MAX_DT: f32 = 0.033  -- max 33ms (30fps minimum)\n\n"
        "entry {\n    -- ...\n    loop {\n"
        "        let raw_dt: f32 = timer.delta()\n"
        "        let dt: f32 = raw_dt\n"
        "        if dt > MAX_DT { dt = MAX_DT }  -- cap delta time\n"
        "        -- use capped dt for all physics/animation\n"
        "    }\n}\n```\n\n"
        "**If you miss 60fps target:**\n"
        "1. Reduce polygon count (LOD, cull off-screen objects)\n"
        "2. Reduce entity update frequency (only update AI every 2nd frame)\n"
        "3. Simplify collision detection (fewer checks per frame)\n"
        "4. Move to fixed-point math for bulk calculations\n"
        "5. Consider 30fps target with smoother physics interpolation")

    # === Audio performance ===
    add("How do I avoid audio performance issues on N64?",
        "Audio mixer runs on the CPU (RSP can help via libdragon). Keep it light:\n\n"
        "```pak\nuse n64.audio\nuse n64.mixer\n\n-- keep channel count low\naudio.init(44100, 2)  -- 44.1kHz, 2 buffers\nmixer.init(8)          -- max 8 channels (not 32!)\n\n"
        "-- only play sounds when necessary\nfn play_sfx_if_audible(sfx: *wav64_t,\n"
        "                       src_x: f32, cam_x: f32) {\n"
        "    let dist: f32 = src_x - cam_x\n"
        "    if dist < 0.0 { dist = -dist }\n"
        "    if dist > 200.0 { return }  -- too far, skip\n"
        "    mixer.ch_play(0, sfx)\n}\n\n"
        "-- limit simultaneous sounds\nconst MAX_SFX: i32 = 4  -- max 4 SFX at once\nstatic sfx_count: i32 = 0\n\n"
        "fn play_sfx_limited(sfx: *wav64_t) {\n"
        "    if sfx_count >= MAX_SFX { return }\n"
        "    mixer.ch_play(sfx_count, sfx)\n"
        "    sfx_count = sfx_count + 1\n}\n```\n\n"
        "**Sample rate tradeoffs:**\n"
        "- 44100Hz: best quality, highest CPU cost\n"
        "- 22050Hz: half the CPU cost, acceptable quality\n"
        "- 11025Hz: quarter CPU cost, noticeably worse quality")

    # === DMA performance ===
    add("How do I use DMA efficiently for streaming data from ROM?",
        "DMA transfers are asynchronous — overlap with CPU work:\n\n"
        "```pak\nuse n64.dma\nuse n64.cache\n\n"
        "@aligned(16)\nstatic buf_a: [u8; 2048] = undefined\n"
        "@aligned(16)\nstatic buf_b: [u8; 2048] = undefined\n\n"
        "-- double-buffering pattern: read next while processing current\n"
        "fn stream_tiles(rom_base: u32, total: i32) {\n"
        "    let current: i32 = 0\n"
        "    let use_a: bool = true\n\n"
        "    -- start first DMA\n"
        "    cache.writeback(&buf_a[0], 2048)\n"
        "    dma.read(&buf_a[0], rom_base, 2048)\n\n"
        "    loop {\n"
        "        if current >= total { break }\n\n"
        "        if use_a {\n"
        "            -- start next DMA into buf_b\n"
        "            if current + 1 < total {\n"
        "                cache.writeback(&buf_b[0], 2048)\n"
        "                dma.read(&buf_b[0], rom_base + 2048, 2048)\n"
        "            }\n"
        "            -- wait for buf_a and process it\n"
        "            dma.wait()\n"
        "            cache.invalidate(&buf_a[0], 2048)\n"
        "            -- process buf_a here\n"
        "        } else {\n"
        "            if current + 1 < total {\n"
        "                cache.writeback(&buf_a[0], 2048)\n"
        "                dma.read(&buf_a[0], rom_base + 4096, 2048)\n"
        "            }\n"
        "            dma.wait()\n"
        "            cache.invalidate(&buf_b[0], 2048)\n"
        "            -- process buf_b here\n"
        "        }\n        use_a = not use_a\n"
        "        current = current + 1\n    }\n}\n```")

    return pairs
