"""Deep tiny3d (t3d) knowledge: 3D pipeline, models, skeleton, animation, math, lighting, scenes."""


def gen_t3d_deep() -> list[dict]:
    pairs = []

    def add(instruction, output):
        pairs.append({"instruction": instruction, "output": output,
                       "source": "generated", "category": "t3d_deep"})

    # === Full 3D Pipeline ===
    add("What is the complete t3d rendering pipeline in Pak?",
        "The full t3d frame pipeline:\n\n"
        "```pak\nuse n64.display\nuse n64.rdpq\nuse t3d\n\n"
        "entry {\n"
        "    display.init(0, 2, 3, 0, 1)\n"
        "    rdpq.init()\n"
        "    t3d.init()\n\n"
        "    let vp: T3DViewport = t3d.viewport_create()\n"
        "    t3d.viewport_set_projection(&vp, 70.0, 1.0, 100.0)\n\n"
        "    let model: *T3DModel = t3d.model_load(\"models/obj.t3dm\")\n\n"
        "    let mat: T3DMat4 = undefined\n"
        "    t3d.mat4_identity(&mat)\n\n"
        "    loop {\n"
        "        let fb = display.get()\n"
        "        rdpq.attach_clear(fb)\n\n"
        "        t3d.frame_start()\n"
        "        t3d.viewport_attach(&vp)\n\n"
        "        -- set lighting before drawing\n"
        "        t3d.light_set_ambient(50, 50, 50)\n"
        "        t3d.light_set_directional(0, 255, 255, 255, 0.0, -1.0, 0.5)\n"
        "        t3d.light_set_count(1)\n\n"
        "        t3d.model_draw(model)\n\n"
        "        t3d.frame_end()\n"
        "        rdpq.detach_show()\n"
        "    }\n}\n```\n\n"
        "Order matters: init t3d after rdpq, frame_start before viewport_attach, "
        "lighting before draw, frame_end before detach_show.")

    # === Viewport and Projection ===
    add("How do I set up a t3d viewport with custom FOV and clipping in Pak?",
        "```pak\nuse t3d\n\n"
        "let vp: T3DViewport = t3d.viewport_create()\n\n"
        "-- fov in degrees, near and far clipping planes\n"
        "t3d.viewport_set_projection(&vp, 45.0, 0.5, 200.0)\n\n"
        "-- change FOV dynamically (e.g. zoom effect)\n"
        "t3d.viewport_set_fov(&vp, 30.0)  -- narrow FOV = zoom in\n"
        "t3d.viewport_set_fov(&vp, 90.0)  -- wide FOV = fish-eye\n```\n\n"
        "Common FOV values: 45 (tight), 60 (standard), 70 (wide), 90 (very wide). "
        "Near plane should be > 0.1 to avoid Z-fighting. Far plane affects Z-buffer "
        "precision -- keep it as small as your scene allows.")

    add("How do I implement a split-screen viewport in Pak?",
        "Create two viewports with different screen regions using t3d.screen_projection:\n\n"
        "```pak\nuse t3d\nuse n64.display\nuse n64.rdpq\n\n"
        "let vp1: T3DViewport = t3d.viewport_create()\n"
        "let vp2: T3DViewport = t3d.viewport_create()\n\n"
        "t3d.viewport_set_projection(&vp1, 70.0, 1.0, 100.0)\n"
        "t3d.viewport_set_projection(&vp2, 70.0, 1.0, 100.0)\n\n"
        "-- in render loop:\n"
        "let fb = display.get()\n"
        "rdpq.attach_clear(fb)\n\n"
        "-- player 1 (top half)\n"
        "t3d.frame_start()\n"
        "t3d.screen_projection(0, 0, 320, 120)  -- top half\n"
        "t3d.viewport_attach(&vp1)\n"
        "-- draw player 1 scene\n"
        "t3d.model_draw(model)\n"
        "t3d.frame_end()\n\n"
        "-- player 2 (bottom half)\n"
        "t3d.frame_start()\n"
        "t3d.screen_projection(0, 120, 320, 120)  -- bottom half\n"
        "t3d.viewport_attach(&vp2)\n"
        "-- draw player 2 scene\n"
        "t3d.model_draw(model)\n"
        "t3d.frame_end()\n\n"
        "rdpq.detach_show()\n```")

    # === Model Loading and Objects ===
    add("How do I load and draw multiple 3D models in Pak?",
        "```pak\nuse t3d\n\n"
        "-- load models (converted from .glb/.gltf to .t3dm by build system)\n"
        "let player_model: *T3DModel = t3d.model_load(\"models/player.t3dm\")\n"
        "let enemy_model: *T3DModel = t3d.model_load(\"models/enemy.t3dm\")\n"
        "let level_model: *T3DModel = t3d.model_load(\"models/level.t3dm\")\n\n"
        "-- each model needs its own transform matrix\n"
        "let player_mat: T3DMat4 = undefined\n"
        "let enemy_mat: T3DMat4 = undefined\n"
        "let level_mat: T3DMat4 = undefined\n"
        "t3d.mat4_identity(&player_mat)\n"
        "t3d.mat4_identity(&enemy_mat)\n"
        "t3d.mat4_identity(&level_mat)\n\n"
        "-- draw in render loop:\n"
        "t3d.model_draw(level_model)   -- draw level first (background)\n"
        "t3d.model_draw(enemy_model)\n"
        "t3d.model_draw(player_model)  -- draw player last\n```\n\n"
        "Models are loaded from DragonFS (ROM). The .t3dm format is optimized "
        "for N64 hardware with pre-computed display lists.")

    add("How do I draw specific sub-objects from a t3d model in Pak?",
        "Models can contain multiple named objects. Use t3d.draw_object for selective drawing:\n\n"
        "```pak\nuse t3d\n\nextern \"C\" {\n"
        "    fn t3d_model_get_object(model: *T3DModel, name: *c_char) -> *T3DObject\n}\n\n"
        "let model: *T3DModel = t3d.model_load(\"models/character.t3dm\")\n\n"
        "-- get named objects from the model\n"
        "let body: *T3DObject = t3d_model_get_object(model, \"body\")\n"
        "let weapon: *T3DObject = t3d_model_get_object(model, \"sword\")\n"
        "let shield: *T3DObject = t3d_model_get_object(model, \"shield\")\n\n"
        "-- draw selectively\n"
        "t3d.draw_object(body)    -- always draw body\n"
        "if has_sword {\n    t3d.draw_object(weapon)\n}\n"
        "if has_shield {\n    t3d.draw_object(shield)\n}\n```\n\n"
        "Object names come from your 3D editor (Blender, etc). This is useful for "
        "equipment systems, damage models, or LOD switching.")

    # === Skeleton and Animation ===
    add("How do I set up skeleton animation in t3d?",
        "```pak\nuse t3d\n\n"
        "let model: *T3DModel = t3d.model_load(\"models/character.t3dm\")\n\n"
        "-- create skeleton from model's bone hierarchy\n"
        "let skel: T3DSkeleton = t3d.skeleton_create(model)\n\n"
        "-- create animation clip by name (defined in .glb file)\n"
        "let idle_anim: T3DAnim = t3d.anim_create(model, \"idle\")\n"
        "let run_anim: T3DAnim = t3d.anim_create(model, \"run\")\n\n"
        "-- attach animation to skeleton\n"
        "t3d.anim_attach(&idle_anim, &skel)\n"
        "t3d.anim_set_playing(&idle_anim, true)\n"
        "t3d.anim_set_looping(&idle_anim, true)\n"
        "t3d.anim_set_speed(&idle_anim, 1.0)\n\n"
        "-- per frame:\n"
        "t3d.anim_update(&idle_anim, dt)\n"
        "t3d.skeleton_update(&skel)\n"
        "t3d.skeleton_draw(&skel, model)\n```\n\n"
        "Animation names come from your 3D file. Each skeleton can have one active "
        "animation attached at a time.")

    add("How do I switch between animations in t3d?",
        "Detach the current animation and attach the new one:\n\n"
        "```pak\nuse t3d\n\n"
        "enum AnimState { idle, running, jumping, attacking }\n\n"
        "static current_state: AnimState = AnimState.idle\n\n"
        "fn switch_animation(skel: *T3DSkeleton, old_anim: *T3DAnim,\n"
        "                    new_anim: *T3DAnim, do_loop: bool) {\n"
        "    t3d.anim_set_playing(old_anim, false)\n"
        "    t3d.anim_attach(new_anim, skel)\n"
        "    t3d.anim_set_playing(new_anim, true)\n"
        "    t3d.anim_set_looping(new_anim, do_loop)\n"
        "    t3d.anim_set_speed(new_anim, 1.0)\n}\n\n"
        "-- usage:\n"
        "if current_state != AnimState.running and is_moving {\n"
        "    switch_animation(&skel, &idle_anim, &run_anim, true)\n"
        "    current_state = AnimState.running\n"
        "}\n```")

    add("How do I control animation playback speed in t3d?",
        "```pak\nuse t3d\n\n"
        "-- normal speed\n"
        "t3d.anim_set_speed(&anim, 1.0)\n\n"
        "-- half speed (slow motion)\n"
        "t3d.anim_set_speed(&anim, 0.5)\n\n"
        "-- double speed\n"
        "t3d.anim_set_speed(&anim, 2.0)\n\n"
        "-- reverse playback\n"
        "t3d.anim_set_speed(&anim, -1.0)\n\n"
        "-- speed based on movement (walk/run blend)\n"
        "let speed: f32 = player_velocity / max_walk_speed\n"
        "t3d.anim_set_speed(&walk_anim, speed)\n```\n\n"
        "Speed is a multiplier on the animation's base rate. Use dt-based "
        "update for frame-rate independent animation.")

    # === Matrix Math ===
    add("How do I build a transform matrix for a 3D object in Pak?",
        "Combine scale, rotation, and translation matrices:\n\n"
        "```pak\nuse t3d\n\nstruct Transform {\n"
        "    x: f32\n    y: f32\n    z: f32\n"
        "    rot_x: f32\n    rot_y: f32\n    rot_z: f32\n"
        "    scale: f32\n}\n\n"
        "fn build_matrix(t: *Transform, out: *T3DMat4) {\n"
        "    let tmp: T3DMat4 = undefined\n\n"
        "    -- start with identity\n"
        "    t3d.mat4_identity(out)\n\n"
        "    -- apply scale\n"
        "    t3d.mat4_scale(out, t.scale, t.scale, t.scale)\n\n"
        "    -- apply rotation (order: Z, X, Y is common for games)\n"
        "    t3d.mat4_rotate_z(&tmp, t.rot_z)\n"
        "    t3d.mat4_mul(out, out, &tmp)\n"
        "    t3d.mat4_rotate_x(&tmp, t.rot_x)\n"
        "    t3d.mat4_mul(out, out, &tmp)\n"
        "    t3d.mat4_rotate_y(&tmp, t.rot_y)\n"
        "    t3d.mat4_mul(out, out, &tmp)\n\n"
        "    -- apply translation\n"
        "    t3d.mat4_translate(&tmp, t.x, t.y, t.z)\n"
        "    t3d.mat4_mul(out, out, &tmp)\n}\n```\n\n"
        "Matrix multiplication order matters. Scale first, then rotate, then translate.")

    add("How do I use vector math in t3d?",
        "```pak\nuse t3d\n\n"
        "-- normalize a direction vector\n"
        "let dir: T3DVec3 = undefined\n"
        "dir.x = 3.0\ndir.y = 0.0\ndir.z = 4.0\n"
        "let norm: T3DVec3 = undefined\n"
        "t3d.vec3_norm(&norm, &dir)  -- norm is now (0.6, 0, 0.8)\n\n"
        "-- dot product (angle between vectors)\n"
        "let dot: f32 = t3d.vec3_dot(&a, &b)\n"
        "-- dot > 0: same direction, dot < 0: opposite, dot == 0: perpendicular\n\n"
        "-- cross product (perpendicular vector)\n"
        "let up: T3DVec3 = undefined\n"
        "t3d.vec3_cross(&up, &forward, &right)\n```\n\n"
        "T3DVec3 has fields x, y, z (all f32). These are the core operations "
        "for camera systems, collision normals, and movement direction.")

    # === Lighting ===
    add("How do I set up multiple lights in t3d?",
        "```pak\nuse t3d\n\n"
        "fn setup_lighting() {\n"
        "    -- ambient light (always present, no direction)\n"
        "    t3d.light_set_ambient(30, 30, 40)  -- dark blue-ish ambient\n\n"
        "    -- directional light 0: main sun\n"
        "    t3d.light_set_directional(0, 255, 240, 200,   -- warm white\n"
        "        -0.5, -1.0, 0.3)  -- direction (normalized internally)\n\n"
        "    -- directional light 1: fill light\n"
        "    t3d.light_set_directional(1, 80, 80, 120,     -- cool blue\n"
        "        0.5, -0.3, -0.5)\n\n"
        "    -- tell t3d how many directional lights are active\n"
        "    t3d.light_set_count(2)\n}\n```\n\n"
        "N64 supports up to 7 directional lights plus ambient. More lights = more "
        "RSP processing. 1-2 directional lights is typical for good performance.")

    add("How do I change lighting dynamically for day/night in Pak?",
        "```pak\nuse t3d\n\nstruct DayNightCycle {\n"
        "    time: f32      -- 0.0 to 1.0 (0=midnight, 0.5=noon)\n"
        "    speed: f32\n}\n\n"
        "fn update_lighting(cycle: *DayNightCycle, dt: f32) {\n"
        "    cycle.time = cycle.time + cycle.speed * dt\n"
        "    if cycle.time > 1.0 { cycle.time = cycle.time - 1.0 }\n\n"
        "    -- sun direction rotates with time\n"
        "    let sun_y: f32 = -1.0 + cycle.time * 2.0  -- simplified\n\n"
        "    -- ambient changes: dark at night, bright at noon\n"
        "    let amb: u8 = (30.0 + 50.0 * cycle.time) as u8\n"
        "    t3d.light_set_ambient(amb, amb, amb + 10 as u8)\n\n"
        "    -- sun color: orange at dawn/dusk, white at noon\n"
        "    let r: u8 = 255\n    let g: u8 = (200.0 + 55.0 * cycle.time) as u8\n"
        "    let b: u8 = (150.0 + 105.0 * cycle.time) as u8\n"
        "    t3d.light_set_directional(0, r, g, b, -0.3, sun_y, 0.5)\n}\n```")

    # === Camera Systems ===
    add("How do I build a third-person camera in Pak with t3d?",
        "```pak\nuse t3d\n\nstruct ThirdPersonCamera {\n"
        "    target_x: f32\n    target_y: f32\n    target_z: f32\n"
        "    distance: f32\n    pitch: f32\n    yaw: f32\n"
        "    x: f32\n    y: f32\n    z: f32\n}\n\n"
        "impl ThirdPersonCamera {\n"
        "    fn init(self: *ThirdPersonCamera) {\n"
        "        self.distance = 15.0\n        self.pitch = 0.3\n"
        "        self.yaw = 0.0\n    }\n\n"
        "    fn update(self: *ThirdPersonCamera, tx: f32, ty: f32, tz: f32,\n"
        "              stick_x: f32, stick_y: f32, dt: f32) {\n"
        "        self.target_x = tx\n        self.target_y = ty\n"
        "        self.target_z = tz\n\n"
        "        -- rotate camera with analog stick\n"
        "        self.yaw = self.yaw + stick_x * dt * 2.0\n"
        "        self.pitch = self.pitch + stick_y * dt * 1.0\n"
        "        if self.pitch < 0.1 { self.pitch = 0.1 }\n"
        "        if self.pitch > 1.2 { self.pitch = 1.2 }\n\n"
        "        -- compute camera position on sphere around target\n"
        "        -- simplified: uses pitch as elevation, yaw as rotation\n"
        "        self.x = tx + self.distance * self.pitch * self.yaw\n"
        "        self.y = ty + self.distance * self.pitch\n"
        "        self.z = tz + self.distance * self.pitch\n    }\n\n"
        "    fn get_view_matrix(self: *ThirdPersonCamera, out: *T3DMat4) {\n"
        "        t3d.mat4_identity(out)\n"
        "        t3d.mat4_rotate_y(out, -self.yaw)\n"
        "        t3d.mat4_rotate_x(out, -self.pitch)\n"
        "        t3d.mat4_translate(out, -self.x, -self.y, -self.z)\n"
        "    }\n}\n```")

    add("How do I build a first-person camera in Pak?",
        "```pak\nuse t3d\n\nstruct FPSCamera {\n"
        "    x: f32\n    y: f32\n    z: f32\n"
        "    yaw: f32\n    pitch: f32\n"
        "    move_speed: f32\n    look_speed: f32\n}\n\n"
        "impl FPSCamera {\n"
        "    fn init(self: *FPSCamera) {\n"
        "        self.x = 0.0\n        self.y = 2.0\n        self.z = 0.0\n"
        "        self.yaw = 0.0\n        self.pitch = 0.0\n"
        "        self.move_speed = 10.0\n        self.look_speed = 2.0\n"
        "    }\n\n"
        "    fn update(self: *FPSCamera, pad: *controller_data, dt: f32) {\n"
        "        -- look with C buttons\n"
        "        if pad.held.c_left { self.yaw = self.yaw + self.look_speed * dt }\n"
        "        if pad.held.c_right { self.yaw = self.yaw - self.look_speed * dt }\n"
        "        if pad.held.c_up { self.pitch = self.pitch + self.look_speed * dt }\n"
        "        if pad.held.c_down { self.pitch = self.pitch - self.look_speed * dt }\n\n"
        "        -- clamp pitch\n"
        "        if self.pitch > 1.2 { self.pitch = 1.2 }\n"
        "        if self.pitch < -1.2 { self.pitch = -1.2 }\n\n"
        "        -- move with analog stick (relative to facing)\n"
        "        let sx: i32 = pad.stick_x as i32\n"
        "        let sy: i32 = pad.stick_y as i32\n"
        "        let fx: f32 = (sx as f32) / 80.0\n"
        "        let fy: f32 = (sy as f32) / 80.0\n\n"
        "        self.z = self.z + fy * self.move_speed * dt\n"
        "        self.x = self.x + fx * self.move_speed * dt\n"
        "    }\n\n"
        "    fn get_view_matrix(self: *FPSCamera, out: *T3DMat4) {\n"
        "        t3d.mat4_identity(out)\n"
        "        t3d.mat4_rotate_x(out, -self.pitch)\n"
        "        t3d.mat4_rotate_y(out, -self.yaw)\n"
        "        t3d.mat4_translate(out, -self.x, -self.y, -self.z)\n"
        "    }\n}\n```")

    # === Scene Management ===
    add("How do I manage a 3D scene with multiple entities in Pak?",
        "```pak\nuse t3d\n\nconst MAX_ENTITIES: i32 = 32\n\n"
        "struct Entity3D {\n"
        "    active: bool\n    model: *T3DModel\n"
        "    x: f32\n    y: f32\n    z: f32\n"
        "    rot_y: f32\n    scale: f32\n"
        "    mat: T3DMat4\n}\n\n"
        "static entities: [Entity3D; 32] = undefined\n"
        "static entity_count: i32 = 0\n\n"
        "fn spawn_entity(model: *T3DModel, x: f32, y: f32, z: f32) -> i32 {\n"
        "    if entity_count >= MAX_ENTITIES { return -1 }\n"
        "    let idx: i32 = entity_count\n"
        "    entities[idx].active = true\n"
        "    entities[idx].model = model\n"
        "    entities[idx].x = x\n    entities[idx].y = y\n    entities[idx].z = z\n"
        "    entities[idx].rot_y = 0.0\n    entities[idx].scale = 1.0\n"
        "    t3d.mat4_identity(&entities[idx].mat)\n"
        "    entity_count = entity_count + 1\n"
        "    return idx\n}\n\n"
        "fn update_entity_matrices() {\n"
        "    let i: i32 = 0\n"
        "    loop {\n        if i >= entity_count { break }\n"
        "        if entities[i].active {\n"
        "            let tmp: T3DMat4 = undefined\n"
        "            t3d.mat4_identity(&entities[i].mat)\n"
        "            t3d.mat4_scale(&entities[i].mat, entities[i].scale,\n"
        "                           entities[i].scale, entities[i].scale)\n"
        "            t3d.mat4_rotate_y(&tmp, entities[i].rot_y)\n"
        "            t3d.mat4_mul(&entities[i].mat, &entities[i].mat, &tmp)\n"
        "            t3d.mat4_translate(&tmp, entities[i].x, entities[i].y, entities[i].z)\n"
        "            t3d.mat4_mul(&entities[i].mat, &entities[i].mat, &tmp)\n"
        "        }\n        i = i + 1\n    }\n}\n\n"
        "fn draw_all_entities() {\n"
        "    let i: i32 = 0\n"
        "    loop {\n        if i >= entity_count { break }\n"
        "        if entities[i].active {\n"
        "            t3d.model_draw(entities[i].model)\n"
        "        }\n        i = i + 1\n    }\n}\n```")

    # === Model pipeline ===
    add("How do I prepare 3D models for t3d on N64?",
        "T3D uses .t3dm model format converted from glTF/GLB files:\n\n"
        "1. **Create models** in Blender (recommended) or any glTF exporter\n"
        "2. **Export as .glb** (binary glTF)\n"
        "3. **Convert with t3d tools**: the build system converts .glb to .t3dm\n"
        "4. **Load in Pak**: `t3d.model_load(\"models/name.t3dm\")`\n\n"
        "**Blender tips for N64:**\n"
        "- Keep polygon count low: 100-500 tris per object is ideal\n"
        "- Use vertex colors instead of complex textures when possible\n"
        "- Textures must be power-of-2 (16x16, 32x32, 64x64, etc)\n"
        "- Max texture size: 64x64 for 16-bit, 32x32 for 32-bit (TMEM limit)\n"
        "- Name objects in Blender for t3d_model_get_object access\n"
        "- Name animations in Blender for t3d.anim_create access\n"
        "- Keep bone count under 30 per skeleton for performance\n\n"
        "**Memory budget**: a typical character model with textures uses 5-20KB. "
        "A full level might use 50-200KB. Stay within 2-3MB total for models.")

    add("How do I handle model LOD (level of detail) in t3d?",
        "T3D doesn't have built-in LOD. Implement manually with distance checks:\n\n"
        "```pak\nuse t3d\n\nstruct LODModel {\n"
        "    high: *T3DModel    -- close range\n"
        "    medium: *T3DModel  -- mid range\n"
        "    low: *T3DModel     -- far range\n"
        "    lod_dist_med: f32  -- switch to medium at this distance\n"
        "    lod_dist_low: f32  -- switch to low at this distance\n}\n\n"
        "fn draw_lod(lod: *LODModel, cam_x: f32, cam_z: f32,\n"
        "            obj_x: f32, obj_z: f32) {\n"
        "    let dx: f32 = cam_x - obj_x\n"
        "    let dz: f32 = cam_z - obj_z\n"
        "    let dist_sq: f32 = dx * dx + dz * dz\n\n"
        "    if dist_sq > lod.lod_dist_low * lod.lod_dist_low {\n"
        "        t3d.model_draw(lod.low)\n"
        "    } elif dist_sq > lod.lod_dist_med * lod.lod_dist_med {\n"
        "        t3d.model_draw(lod.medium)\n"
        "    } else {\n"
        "        t3d.model_draw(lod.high)\n"
        "    }\n}\n```\n\n"
        "Use squared distance to avoid expensive square root. "
        "3 LOD levels is usually enough for N64.")

    # === Bone Attachments ===
    add("How do I attach objects to skeleton bones in t3d (weapon in hand)?",
        "Get the bone's matrix from the skeleton and use it as the object's transform:\n\n"
        "```pak\nuse t3d\n\nextern \"C\" {\n"
        "    fn t3d_skeleton_get_bone_matrix(skel: *T3DSkeleton, name: *c_char) -> *T3DMat4\n}\n\n"
        "-- attach weapon model to character's hand bone\n"
        "let char_model: *T3DModel = t3d.model_load(\"models/character.t3dm\")\n"
        "let weapon_model: *T3DModel = t3d.model_load(\"models/sword.t3dm\")\n"
        "let skel: T3DSkeleton = t3d.skeleton_create(char_model)\n\n"
        "-- in render:\n"
        "t3d.skeleton_update(&skel)\n"
        "let hand_mat: *T3DMat4 = t3d_skeleton_get_bone_matrix(&skel, \"hand.R\")\n"
        "-- use hand_mat as weapon's world transform\n"
        "-- draw weapon at bone position\n"
        "t3d.skeleton_draw(&skel, char_model)\n"
        "t3d.model_draw(weapon_model)\n```\n\n"
        "Bone names come from your Blender armature. Common names: "
        "\"hand.R\", \"hand.L\", \"head\", \"spine\", \"hip\".")

    # === Cleanup ===
    add("How do I properly clean up t3d resources in Pak?",
        "```pak\nuse t3d\n\n"
        "fn cleanup_3d(model: *T3DModel, skel: *T3DSkeleton,\n"
        "              anim: *T3DAnim) {\n"
        "    -- destroy in reverse order of creation\n"
        "    t3d.anim_set_playing(anim, false)\n"
        "    t3d.anim_destroy(anim)\n"
        "    t3d.skeleton_destroy(skel)\n"
        "    t3d.model_free(model)\n}\n\n"
        "-- when completely done with 3D:\n"
        "fn shutdown_3d() {\n"
        "    -- free all models, skeletons, animations first\n"
        "    t3d.destroy()  -- shutdown t3d library\n"
        "    rdpq.close()   -- then rdpq\n}\n```\n\n"
        "Always destroy animations before skeletons, skeletons before models. "
        "Call t3d.destroy() last after all resources are freed.")

    # === Frustum culling ===
    add("How do I implement basic frustum culling for t3d in Pak?",
        "Do a simple distance + angle check before drawing:\n\n"
        "```pak\nuse t3d\n\n"
        "fn is_visible(cam_x: f32, cam_z: f32, cam_yaw: f32,\n"
        "              obj_x: f32, obj_z: f32, max_dist: f32) -> bool {\n"
        "    let dx: f32 = obj_x - cam_x\n"
        "    let dz: f32 = obj_z - cam_z\n"
        "    let dist_sq: f32 = dx * dx + dz * dz\n\n"
        "    -- distance check\n"
        "    if dist_sq > max_dist * max_dist { return false }\n\n"
        "    -- rough angle check (dot product with view direction)\n"
        "    -- objects behind camera are culled\n"
        "    let view_z: f32 = 1.0  -- simplified forward vector\n"
        "    let dot: f32 = dx * 0.0 + dz * view_z\n"
        "    if dot < 0.0 { return false }  -- behind camera\n\n"
        "    return true\n}\n\n"
        "-- in render loop:\n"
        "let i: i32 = 0\n"
        "loop {\n    if i >= entity_count { break }\n"
        "    if is_visible(cam.x, cam.z, cam.yaw,\n"
        "                  entities[i].x, entities[i].z, 100.0) {\n"
        "        t3d.model_draw(entities[i].model)\n"
        "    }\n    i = i + 1\n}\n```\n\n"
        "This is a rough cull. For complex scenes, use sector-based visibility "
        "or BSP trees. Even a simple distance cull saves significant GPU time.")

    return pairs
